### ISSUE TITLE
Downloding Multiple songs can crash the game

### ISSUE THREAD

**Issue by CodenameColors** [Quaver/Quaver#2780] opened 2020-12-08 04:23 UTC
There is no way to mass download songs that i can tell. So i went with the spam Down key and enter method.

This works fine until a point. There are two reasons i believe it happens.
-One which is the simple answer i downloaded too many things and the game couldn't handle it.
-Two kinda contradicts 1. As i noticed that when mass downloading with this method it seems to not crash as long as i don't touch or use any of the UI. With a lot of the UI notifications on the screen and after i touch the normal game UI it will crash every time. If i just let the UI disappear. Or Unload as i assume since i saw this is monogame. Performance comes back and i can continue the mass download.

**Comment by Swan** [comment] 2021-01-01 18:28
Duplicate of #2345

**Closed by Swan** 2021-01-01 18:28 UTC
