### ISSUE TITLE
Songs don't display in singleplayer

### ISSUE THREAD

**Issue by ValklireSyS** [Quaver/Quaver#4156] opened 2024-05-29 10:31 UTC
### Describe the bug

For some reason, from last time I opened my game as normally, but form the 1400 maps I had only 450 on display. I checked in the songs folder and they are still in there, and since that time I can't  get the game to display the rest of them.

### To Reproduce

Opened the game as normal and it happened.

### Log Files

[Logs.zip](https://github.com/Quaver/Quaver/files/15482935/Logs.zip)

**Comment by Reihynn** [comment] 2024-05-29 10:48
press F5 and wait for it to finish (could take from 10 mins to an hour or so)

**Comment by ValklireSyS** [comment] 2024-05-29 11:30
It worked, thanks for it. But still, it's the second time it happens, but the first time by restarting the computer it solvet itself. Maybe it happens becouse an workshop item updated, but i don't see how it can interfer.

**Comment by AiAe** [comment] 2024-05-30 23:24
There is nothing in the logs you provided for us to know what the issue is.
The only logs I see is that the game has created the database and that it found 1843 maps.

I will close the issue, without better logs/replication of the issue we cannot do much.

**Closed by AiAe** 2024-05-30 23:24 UTC
Labels: Bug
