### ISSUE TITLE
Resolution is not optimized

### ISSUE THREAD

**Issue by NehkoPoi** [Quaver/Quaver#2263] opened 2020-07-10 17:25 UTC
**Describe the bug**
Changing resolution in borderless or fullscreen mode ( 1920 x 1080 ) causes game screen to become offcentered and out of screen

**To Reproduce**
change resolution to 1920x1090

**Comment by Swan** [comment] 2020-07-11 13:02
Duplicate of #362

**Closed by Swan** 2020-07-11 13:02 UTC
