### ISSUE TITLE
Can't see who's inside a multiplayer match from the lobby screen

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#2236] opened 2020-07-04 12:49 UTC
There's no indication of the players who are inside the match, their rank or their country anywhere in the lobby screen. It should be added somewhere, and friends should be highlighted.

**Comment by Janko5** [comment] 2020-07-04 12:57
Known. Design for this exist but must be implemented

**Comment by Swan** [comment] 2020-07-04 13:41
Duplicate of #1343

**Closed by Swan** 2020-07-04 13:41 UTC
