### ISSUE TITLE
Why can't I launch quaver?

### ISSUE THREAD

**Issue by TheGitGudBoi** [Quaver/Quaver#2610] opened 2020-08-30 04:36 UTC
**Describe the bug**
When clicking on the play button, It says is running but after a few seconds, it stopped running.

**To Reproduce**
1. Go to the steam library and pay quaver.
2. wait for a few seconds
3. It should stop running and goes back to the play button.

**Expected behavior**
Quaver should launch

**Screenshots**
![Play button](https://user-images.githubusercontent.com/58142137/91651260-2f35e080-eabd-11ea-9046-3497aa361eab.png)
The play button I'm referring to.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 10.0.19041 Build 19041

**Additional context**
My graphics driver is updated and my desktop meets the system requirements.

**Comment by IceDynamix** [comment] 2020-08-30 06:18
Duplicate of #2248

**Closed** 2020-11-25 21:07 UTC
