### ISSUE TITLE
Separate Skinnable LN Hitsounds

### ISSUE THREAD

**Issue by EpiCreeper** [Quaver/Quaver#4237] opened 2024-07-27 09:52 UTC
### Is your feature request related to a problem? Please describe.

We have LN release hitsounds in Quaver and that's great! The problem is that they sound exactly the same as normal notes, which could feel weird considering holding or releasing a key are different inputs, and can sound weird in certain charts.

### Describe the solution you'd like

By default hitsounds should work as they do now, but if you add separate sounds to your skin folder, holding and releasing a note could use those sounds instead, making for a more dynamic audio feedback loop.

### Describe alternatives you've considered

There could also be an option in the skin.ini to have the hold sound repeat itself until the key is released, similar to other rhythm games like muse dash.
You could also add unique hitsounds when hitting a key without a note for added flavor.

### Additional context

I don't know how that would work with custom chartable hitsounds and I don't know about them to suggest any solutions, sorry

**Comment by Warp9000** [comment] 2024-07-27 09:55
duplicate of https://github.com/Quaver/Quaver/issues/4080

**Comment by EpiCreeper** [comment] 2024-07-27 09:55
oh sorry

**Closed by Warp9000** 2024-07-27 09:55 UTC
Labels: New Feature
