### ISSUE TITLE
Game crashes if you try and enter multiplayer lobby for no apparent reason

### ISSUE THREAD

**Issue by EliteDreamer** [Quaver/Quaver#2992] opened 2021-05-10 22:00 UTC
Describe the bug:
If you try and enter a multiplayer lobby you will crash no matter what

1.Go to multiplayer and select a lobby
2.Someone selects a map (doesn't matter what map)
3.Game client starts visibly lagging (even tho i have 300 fps, but you can clearly see the game stuttering)
4.Quit the lobby and restart quaver
5.Start quaver and join the same lobby with the same song
6.In something like 5 seconds (even less usually) you will crash no matter what

Expected behavior:
The game not crashing, actually the game not lagging in the first place

Screenshots
//

Desktop (please complete the following information):
 - OS: w10
 - Version 19041.928
 - Specs: r5 3600, 1070, 16 gb

Additional context:
Explained everything in the steps to reproduce, want to add that maybe it doesn't even matter if you have the map or you have to download the map or you just downloaded the map, the game will start lagging hard, once you quit you'll not be able to enter the lobby untill the song will be changed, seems also that other people start lagging too and get normal fps once the song ends/is changed. I want to stress that it seems that normal maps are affected by this bug and seems they work fine in other circumstances (solo, other lobbies), or at least they don't affect the game permanently.

**Comment by EliteDreamer** [comment] 2021-05-11 21:44
Update.
Happend again today, didn't leave the lobby but after some time i crashed.
Tried entering again, survived max 10 seconds, crashed.
Tried a second time, happened again.
Tried third time, survived for maybe 1 min at max and have been able to start the game and played normally, after that everything was fine.
The lag starts at [10:14:05] ? Maybe not, it's not instant, maybe 06/07 ? Actually survived 1 min and 3 seconds.Everything normal after.
(bonus issue: a crash at the end of the log, someone selected a map i didn't have everything was normal once i joined again)
[runtime.log](https://github.com/Quaver/Quaver/files/6462068/runtime.log)

**Comment by Illuminati-CRAZ** [comment] 2021-08-07 22:10
duplicate of #2885

**Closed by Illuminati-CRAZ** 2021-08-07 22:10 UTC
