### ISSUE TITLE
Retry hotkey right after failing causes blackscreen (Enter Tap is on)

### ISSUE THREAD

**Issue by Topovn** [Quaver/Quaver#2297] opened 2020-07-11 19:09 UTC
**To Reproduce**
1. Play the map and fail but before entering result screen, spam retry hotkey (R)
- Game will freeze for a brief second and proceeds with a blackscreen and then restart the map
- This score will not be saved
2. You can still make inputs but there is still a blackscreen so you can't see anything
- You can only exit the blackscreen by failing the song so the game will enter result screen

**Expected behavior**
No blackscreen

**Comment by staravia** [comment] 2020-07-11 23:38
duplicate of https://github.com/Quaver/Quaver/issues/2187

**Closed by staravia** 2020-07-11 23:38 UTC
