### ISSUE TITLE
"Perfectionist" Steam Achievement

### ISSUE THREAD

**Issue by InspectorIris** [Quaver/Quaver#2870] opened 2021-03-02 16:15 UTC
Incorrectly received the steam achievement "Perfectionist

**To Reproduce**
1. Start a map,
2. Fail immediately

**Expected behavior**
No achievement received.

**Screenshots**
![image](https://user-images.githubusercontent.com/79927369/109677647-df0d0900-7b47-11eb-8226-30f03e7224c9.png)

**Desktop (please complete the following information):**
 - Windows 10 Home 64
 - Steam ver. 1613176728
 - Quaver ver. 0.27.1

**Additional context**
I am not certain, but I believe the track to have been "Hope" mapped by Shima.
I already saw the initial post here: https://github.com/Quaver/Quaver/issues/2677

**Comment by CelluloidRacer2** [comment] 2021-03-15 22:27
This is probably a duplicate of #2677. I'm not entirely sure why the issue was closed without being confirmed fixed...

**Closed** 2021-08-07 22:12 UTC
