### ISSUE TITLE
[redesign] Alt gr doesn't work

### ISSUE THREAD

**Issue by V3rald** [Quaver/Quaver#1588] opened 2020-02-20 19:08 UTC
You can't insert any special character created with Alt Gr into search text.

I have qwerty keyboard but i use qwertz layout via windows and so i cant press things like <> without the use of Alt Gr

**Comment by Swan** [comment] 2020-11-25 19:30
Duplicate of #858

**Closed by Swan** 2020-11-25 19:30 UTC
Labels: Import, Requires Wobble
