### ISSUE TITLE
Right click to scroll

### ISSUE THREAD

**Issue by Magorx** [Quaver/Quaver#290] opened 2018-12-21 20:12 UTC
**Is your feature request related to a problem? Please describe.**
It is really hard to just scroll with mouse wheel

**Describe the solution you'd like**
Pretty much a feature that does the same thing as in osu so you right click in map select and moves the scroll to the location of mouse

**Comment by Swan** [comment] 2018-12-22 01:10
Duplicate of #289

**Closed by Swan** 2018-12-22 01:10 UTC
Labels: Medium, Requires Wobble, enhancement
