### ISSUE TITLE
I got the "Approaching The Blue Zenith" but i'm not top 100.

### ISSUE THREAD

**Issue by TheGitGudBoi** [Quaver/Quaver#2787] opened 2020-12-15 04:30 UTC
**Describe the bug**
While playing 7k, I suddenly see my global rank as 2 and country rank as 1, as well as I got the Approaching The Blue Zenith achievement. But the quaver website shows otherwise. (The rank on the quaver website is real.)

**To Reproduce**
It just happened on the third 7k map I played during my session.

**Expected behavior**
Nothing else other than my real rank.

**Desktop (please complete the following information):**
 - Microsoft Windows 10 Pro
 - Chrome
 - 10.0.19041 Build 19041

**Comment by chirijikaiser** [comment] 2020-12-15 04:55
This bug has been mentioned in previous issues before, so please be sure to check if you may have or may have not the same result as others. Thank you for your cooperation. You may close this thread.

**Comment by Swan** [comment] 2021-01-01 18:31
Duplicate of #2621

**Closed by Swan** 2021-01-01 18:31 UTC
