### ISSUE TITLE
Network stops working on Fedora 36

### ISSUE THREAD

**Issue by korewaChino** [Quaver/Quaver#3418] opened 2022-03-12 09:43 UTC
**Describe the bug**
Authentication fails with error 1015. Song downloader fails trying to parse JSON
**To Reproduce**
1. Install Fedora Linux 36
2. Play Quaver
3. Attempt to log in or download new songs

**Expected behavior**
Networking features work properly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Version: 0.31.3

**Additional context**
Using native RPMFusion Steam

**Comment by Swan** [comment] 2022-03-13 18:46
@YaLTeR

**Comment by YaLTeR** [comment] 2022-03-13 19:18
We've discussed it in Discord and as far as I remember Quaver running in Flathub Steam works fine. I think we can therefore close this; it would certainly be nice to debug and possibly fix whatever the problem is, but I don't think an open issue is needed for it.

**Closed by YaLTeR** 2022-03-13 19:18 UTC
Labels: Linux
