### ISSUE TITLE
First Several Long Notes When Testplaying From Editor Are Sometimes Visually Short

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#2018] opened 2020-05-20 22:35 UTC
It seems upon test playing a map from the editor, the first few long notes are shown to end sooner than they should, but gameplay wise remain the same length.

**Comment by IceDynamix** [comment] 2020-05-20 22:49
duplicate of https://github.com/Quaver/Quaver/issues/1872

**Closed** 2020-05-21 13:13 UTC
