### ISSUE TITLE
Show map rank in the PB row

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#576] opened 2019-02-22 14:53 UTC
![image](https://user-images.githubusercontent.com/1794388/53250068-b802dd80-36ca-11e9-896f-983ca7bfeb83.png)
The map rank (so global # or friends/whatever # once that's implemented) would be really nice here so you don't have to scroll down and find yourself.

**Comment by Swan** [comment] 2019-02-22 15:01
Duplicate of #364

**Closed by Swan** 2019-02-22 15:01 UTC
