### ISSUE TITLE
Option to disable windows key during gameplay

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#2068] opened 2020-05-29 20:10 UTC
😠
![0qyz9Mg](https://user-images.githubusercontent.com/51453670/83300937-83e96700-a201-11ea-9ee5-8ae60b6f0bb5.jpg)
😠😠😠😠😠

actually not sure if it can be disabled from the game lol

**Comment by IceDynamix** [comment] 2020-05-29 20:28
a few quick fixes you can try

1. pop out the keycap for the windows key, this makes hitting it more unlikely, but still possible if needed
2. (windows only) use autohotkey to set up a quick script that prevents windows key inputs if the active window is quaver (not sure how cool quaver is with ahk)

**Comment by robby250** [comment] 2020-05-29 20:38
Yeah I have a game mode on my keyboard which disables windows key but I didn't use it because I haven't had the problem of hitting it, until this score. And I wanted an option that only disables windows key during gameplay, not during menus, which isn't possible with AHK. I'll close this anyway

**Comment by YaLTeR** [comment] 2020-05-30 03:32
Yes it can be disabled, there's a Windows call for that specifically

**Comment by Sadkawt** [comment] 2020-06-09 08:30
Also ran into this problem today. :-(
I know that Osu automatically disables the win key during gameplay so would be really nice to have in Quaver too. :-))

**Comment by robby250** [comment] 2020-06-09 08:37
Yeah it probably shouldn't be an option it should just do that by default, I don't think there's anyone who wants to suddenly use the windows key during gameplay. Block it while unpaused, and allow it while paused or in the menus.

**Comment by Swan** [comment] 2020-11-25 20:39
Duplicate of #935

**Closed by Swan** 2020-11-25 20:39 UTC
