### ISSUE TITLE
Song list on Download Window Stacks by Keymode

### ISSUE THREAD

**Issue by KaidenFrizu** [Quaver/Quaver#923] opened 2019-07-06 15:26 UTC
**Describe the bug**
Similar to #661 the song list stacks however, it can be also reproduced by the ff:

**To Reproduce**
1. Go to "Download Maps"
2. While the computer is "Searching for Mapsets", quickly select the game mode from 4 keys to 7 keys while it's still searching. The bug will not appear when clicked where the searching is already finished. Best timed on a (quite) slow internet connection.

**Expected behavior**
One song per tab

**Screenshots**
![stack](https://user-images.githubusercontent.com/39328974/60758117-08f5eb80-a046-11e9-9dcf-e804731a0d70.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Version: canary (as of 7/6)

**Comment by KaidenFrizu** [comment] 2019-07-06 15:29
PS. My bad for the screenshot. I'm supposed to take my first display only

**Comment by Swan** [comment] 2019-07-06 16:57
Duplicate of #908

**Closed by Swan** 2019-07-06 16:57 UTC
