### ISSUE TITLE
SillyFanBoy: Minor Features I thought were over looked For Chart Editor

### ISSUE THREAD

**Issue by Hubert0987** [Quaver/Quaver#2381] opened 2020-07-15 03:28 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is a big focus on mouse movements to get things done, workflow impeded switching from hands on keyboard to mouse.

**Describe the solution you'd like**
More customizable keybinds for editor functions already implemented and assigned (specifically noted, move to start/end of chart).
Ability to change snaps, place down notes, switch between regular notes/LN/select (as referenced in #2073) as keybinds.

Outside of keyboard customization, ability to change scrolling direction with mouse wheel

**Additional context**
Posting at SillyFanBoy's request, any further inquiries contact on Discord at SillyFanBoy#6611 .

**Comment by Swan** [comment] 2020-11-25 20:58
Duplicate of #892

**Closed by Swan** 2020-11-25 20:58 UTC
Labels: Editor, Input
