### ISSUE TITLE
Lane Cover didn't work well

### ISSUE THREAD

**Issue by PonBoar** [Quaver/Quaver#2425] opened 2020-07-18 10:15 UTC
**Describe the bug**
After switching screen resolution, the lane cover doesn't cover the whole area (only worked in  1360*768).

**Expected behavior**
1360*768 screenshot

![image](https://user-images.githubusercontent.com/46189505/87850370-42805880-c922-11ea-9a6d-a45fba4bb7b1.png)

**Screenshots**
After switched the screen resolution(1152*864) . 

![image](https://user-images.githubusercontent.com/46189505/87850388-70fe3380-c922-11ea-8e23-56bf6ae67c33.png)

**Comment by Swan** [comment] 2020-07-18 14:19
Duplicate of #2303

**Closed by Swan** 2020-07-18 14:19 UTC
