### ISSUE TITLE
Audio Post-Processing, Volume Normalization

### ISSUE THREAD

**Issue by jojonoyume** [Quaver/Quaver#2417] opened 2020-07-17 17:02 UTC
**Is your feature request related to a problem? Please describe.**

- Many charts have music files that vary in volume, resulting in having to adjust game volume every so often. It also leads to inconsistency with the volume of hitsounds in correlation to the song that is being played; tweaking volume to get that balance to a comfortable point is tedious, personally.

**Describe the solution you'd like**

- Optional post-processing of output audio within the game client, for the purpose of keeping the perceivable loudness between songs consistent. A compressor would be neat. An auto-gain effect could work to a lesser degree.

**Describe alternatives you've considered**

- Being able to save Music/Effect volume mix settings for each map/song, so as to not have to remember what volume settings one used for a certain song.

**Additional context**

- Perceivable loudness, LUFS.

**Comment by Swan** [comment] 2020-07-18 14:15
Duplicate of #2357

**Closed by Swan** 2020-07-18 14:15 UTC
