### ISSUE TITLE
Timing Signatures

### ISSUE THREAD

**Issue by WinterIsPretty** [Quaver/Quaver#2341] opened 2020-07-13 02:23 UTC
**Is your feature request related to a problem? Please describe.**
I can't even add waltz timing points makes it a bit harder for mapping

**Describe the solution you'd like**
the ability to type in the timing signature you need so you can also add exotic ones like 9/8 or 2/4

**Describe alternatives you've considered**
there are none

**Additional context**
none

**Comment by YaLTeR** [comment] 2020-07-13 10:32
Duplicate of #602

**Closed by YaLTeR** 2020-07-13 10:32 UTC
