### ISSUE TITLE
Sound stops working if you plug in or unplug headphones

### ISSUE THREAD

**Issue by megaman15** [Quaver/Quaver#3423] opened 2022-03-15 23:37 UTC
**Describe the bug**
When you unplug headphones or plug in headphones, the sound just quits.
**To Reproduce**
1. get headphones
2. plug them in while game is active and using speakers
3. witness as no sound plays through anything

**Expected behavior**
i expected that when i plug in headphones that it would start to play sound through them

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11 home
 - Browser Opera 
 - Version 21H1

**Additional context**

**Comment by Illuminati-CRAZ** [comment] 2022-03-16 00:43
duplicate of #569

**Closed by Illuminati-CRAZ** 2022-03-16 00:43 UTC
