### ISSUE TITLE
The game launched up and it can't stop by Steam Library plus no first launch setup didn't shown up

### ISSUE THREAD

**Issue by Kaos0422** [Quaver/Quaver#2421] opened 2020-07-18 02:36 UTC
**Describe the bug**
Click "Play" in Steam Library then it keep running, didn't running setups, when I click "Stop" it didn't stop in Steam Library 

**To Reproduce**
1. Click "Play"
2. Running for a while, but the game didn't launched up
3. Click "Stop" it didn't stop

**Expected behavior**
Giving setups for first time starting the game

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bits

**Additional Information**
Didn't saw Quaver in Task Manager, but the Steam Library shown it's running

**Comment by Swan** [comment] 2020-07-18 14:17
Duplicate of #2248

**Closed by Swan** 2020-07-18 14:17 UTC
