### ISSUE TITLE
I Docked my laptop with a monitor and now the sound wont play on my laptop or computer, and it scrolls through songs at the bottom of my screen trying to play them but it just skips them and loops

### ISSUE THREAD

**Issue by RUSSELLAHHHHHH** [Quaver/Quaver#3276] opened 2021-10-16 19:55 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Swan** [comment] 2021-11-15 15:11
Duplicate of #569

**Closed by Swan** 2021-11-15 15:11 UTC
