### ISSUE TITLE
Game won't start, but appears in task manager

### ISSUE THREAD

**Issue by Arbuzzik** [Quaver/Quaver#2490] opened 2020-07-27 20:33 UTC
**Describe the bug**
Clicking the start button, steam says the application is launched, but the game is not launching, but still appearing in task manager.

**To Reproduce**
1. Go to Steam
2. Click on Play
3. Click on Play after 1-2 minutes has pass

**Expected behavior**
The game window appearing, letting me to play the game itself

**Screenshots**
[image](https://user-images.githubusercontent.com/43587118/88588817-d360dd80-d060-11ea-9f43-b3aa12aaba86.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSC
 - Browser: Firefox
 - Version: 0.20.0

**Additional context**
It won't start even after a long time. It worked a couple of days ago by setting Windows 8 compatibility mode, but now even that doesn't work. Also tried installing an older depot, still no success.
Logs from runtime.log:

[11:26:49] - RUNTIME - DEBUG: OS: Microsoft Windows 6.2.9200
[11:26:50] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[11:26:50] - RUNTIME - IMPORTANT: Config file has been successfully read.
[11:26:50] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : Lucrise <76561198263075387>
[11:26:50] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 3 | Entries: 1
[11:26:50] - RUNTIME - IMPORTANT: Config file has been successfully read.
[11:26:50] - RUNTIME - DEBUG: BASS options: DevicePeriod = -1, DeviceBufferLength = 10
[11:26:50] - RUNTIME - DEBUG: BASS version: 2.4.13.8
[11:27:00] - RUNTIME - IMPORTANT: Config file has been successfully read.
[11:27:00] - RUNTIME - IMPORTANT: Scores table has been created
[11:27:00] - RUNTIME - IMPORTANT: Map Database has been created
[11:27:00] - RUNTIME - IMPORTANT: Found 291 .qua files inside the song directory
[11:27:00] - RUNTIME - IMPORTANT: Playlist Table has been created
[11:27:00] - RUNTIME - IMPORTANT: PlaylistMap table has been created
[11:27:00] - RUNTIME - IMPORTANT: QuaverSettings table has been created
[11:27:00] - RUNTIME - IMPORTANT: Found 0 maps that have outdated difficulty ratings. Scheduling recalculation upon enteringselect.
[11:27:00] - RUNTIME - IMPORTANT: JudgementWindows table has been created
[11:27:00] - RUNTIME - IMPORTANT: Created preset judgement windows `Standard*` - Marv: 18 | Perf: 43 | Great: 76 | Good: 106 | Okay: 127 | Miss: 164
[11:27:00] - RUNTIME - IMPORTANT: Created preset judgement windows `Peaceful` - Marv: 23 | Perf: 57 | Great: 101 | Good: 141 | Okay: 169 | Miss: 218
[11:27:00] - RUNTIME - IMPORTANT: Created preset judgement windows `Lenient` - Marv: 21 | Perf: 52 | Great: 91 | Good: 128 | Okay: 153 | Miss: 198
[11:27:00] - RUNTIME - IMPORTANT: Created preset judgement windows `Chill` - Marv: 19 | Perf: 47 | Great: 83 | Good: 116 | Okay: 139 | Miss: 180
[11:27:00] - RUNTIME - IMPORTANT: Created preset judgement windows `Strict` - Marv: 16 | Perf: 39 | Great: 69 | Good: 96 | Okay: 115 | Miss: 149
[11:27:00] - RUNTIME - IMPORTANT: Created preset judgement windows `Tough` - Marv: 14 | Perf: 35 | Great: 62 | Good: 87 | Okay: 104 | Miss: 135
[11:27:00] - RUNTIME - IMPORTANT: Created preset judgement windows `Extreme` - Marv: 13 | Perf: 32 | Great: 57 | Good: 79 | Okay: 95 | Miss: 123
[11:27:00] - RUNTIME - IMPORTANT: Created preset judgement windows `Impossible` - Marv: 8 | Perf: 20 | Great: 35 | Good: 49 | Okay: 59 | Miss: 76
[11:27:00] - RUNTIME - IMPORTANT: UserProfile table has been created
[11:27:00] - RUNTIME - DEBUG: Loaded font: Lato-Regular
[11:27:00] - RUNTIME - DEBUG: Loaded font: Lato-Semibold
[11:27:00] - RUNTIME - DEBUG: Loaded font: Lato-Bold
[11:27:00] - RUNTIME - DEBUG: Loaded font: Lato-Light
[11:27:00] - RUNTIME - DEBUG: Loaded font: Lato-Heavy
[11:27:00] - RUNTIME - DEBUG: Loaded font: Lato-Black

**Comment by Swan** [comment] 2020-07-31 16:27
Duplicate of #2248

**Closed by Swan** 2020-07-31 16:27 UTC
