### ISSUE TITLE
Quaver crashes instantly after entering a multiplayer room (With crash logs)

### ISSUE THREAD

**Issue by ItzKoshepen** [Quaver/Quaver#3134] opened 2021-07-23 10:44 UTC
**Describe the bug**
Has happened multiple times previously, as the title said, Quaver crashes after entering a multiplayer room immediately.

**To Reproduce**
1. Go to Multiplayer section
2. Enter a multiplayer room
3. Wait for 1-3 seconds
4. Quaver crashes

**Expected behavior**
Quaver should proceed to let players stay inside of the multiplayer room instead of crashing

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 0.29.3 [canary]
 
**Additional context**
Quaver crash logs:
[Quaver_Multi_Crash_Log_1.docx](https://github.com/Quaver/Quaver/files/6868195/Quaver_Multi_Crash_Log_1.docx)
[Quaver_Multi_Crash_Log_2.docx](https://github.com/Quaver/Quaver/files/6868196/Quaver_Multi_Crash_Log_2.docx)

**Comment by Illuminati-CRAZ** [comment] 2021-08-07 22:10
duplicate of #2885

**Closed by Illuminati-CRAZ** 2021-08-07 22:10 UTC
