### ISSUE TITLE
Issues with Downloading Songs

### ISSUE THREAD

**Issue by AngelsFear64** [Quaver/Quaver#2532] opened 2020-08-08 06:11 UTC
I downloaded a lot of songs in succession and it seems that none of the songs had actually downloaded, just the keys itself. When I attempt to play a map, I can play the map fine, but there is no audio. When I'm on the main menu, the songs seem to switch repetitively as if the song files hadn't even downloaded or had gotten corrupted. Keep in mind, I can still play the maps, but I can't hear anything and it's almost as if the songs didn't download.

**Comment by Swan** [comment] 2020-08-25 13:19
Duplicate of #569

**Closed by Swan** 2020-08-25 13:19 UTC
