### ISSUE TITLE
Forward Slash fails when referencing non quaver maps in cfg

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#522] opened 2019-02-02 09:23 UTC
Forward-slashes and back-slashes work perfectly when trying to reference another game in the .cfg on both my laptop/PC.

Example (both cases work):
- "OsuDbPath = D:/osu!/osu!.db"
- "OsuDbPath = D:\osu!\osu!.db"

However, trying to use forward-slashes does not work on a specific PC.

- Windows 10
- MSI GTX 1060 6gb
- AMD Ryzen 1800x
- 4x4gb Kingston HyberX Fury DDR4

**Comment by Kangaroux** [comment] 2019-02-21 01:35
What do you mean by, "they do not work on a specific PC"?

**Comment by YaLTeR** [comment] 2019-02-21 06:15
Are you sure you didn't have an extra space in the end or something? Because that's odd

**Comment by staravia** [comment] 2019-02-26 16:26
> Are you sure you didn't have an extra space in the end or something? Because that's odd

No. Literally doing shift+right-click -> copy as path and removing the quotes did not work

**Comment by Swan** [comment] 2020-04-06 15:09
Closing as unable to reproduce

**Closed by Swan** 2020-04-06 15:09 UTC
Labels: Bug, Configuration
