### ISSUE TITLE
Song replay not working correctly

### ISSUE THREAD

**Issue by memegodylan** [Quaver/Quaver#3230] opened 2021-09-07 04:28 UTC
**Describe the bug**
On some songs, if I go back to view the replay, it shows me fail towards the end, the only work around I've found is messing with the playback or skipping to after the point where I fail
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Illuminati-CRAZ** [comment] 2021-09-07 05:03
duplicate of #2331

**Closed by Illuminati-CRAZ** 2021-09-07 05:03 UTC
