### ISSUE TITLE
No Scroll Velocities + View Map Play Testing Bug

### ISSUE THREAD

**Issue by AVY6** [Quaver/Quaver#4201] opened 2024-06-27 21:40 UTC
### Describe the bug

When you enable the No Scroll Velocities modifier and then attempt to play test a Scroll Velocity song, the notes don't have their scroll velocities removed or don't appear at all. 

### To Reproduce

1. Go to Single Player.
2. Click on any SV song.
3. Turn on the No Scroll Velocities modifier.
4. Click on view map.
5. Turn off Autoplay.
6. Done, notes will either continue to move with SV or they just won't appear, depending on the song.

### Expected behavior

I was expecting to be able to practice specific parts of SV songs that I struggle with without having to play the whole song with NSV. I have so many SV songs where there are just 1 or 2 parts that I struggle with, so being forced to play the whole song with NSV to practice sucks. 

### Log Files

.

**Comment by Warp9000** [comment] 2024-06-27 21:44
duplicate of https://github.com/Quaver/Quaver/issues/3785

**Closed by Warp9000** 2024-06-27 21:44 UTC
Labels: Bug

**Comment by AVY6** [comment] 2024-06-28 01:30
So this issue is over a year old and still hasn’t been fixed? What a joke.
