### ISSUE TITLE
Bottom lane cover cut off at the bottom making you see a part of the bottom lane.

### ISSUE THREAD

**Issue by DerRoteVogel** [Quaver/Quaver#3269] opened 2021-10-06 17:49 UTC
**Describe the bug**

When you put the bottom lane cover over 65% you will start to see the bottom part of the lane more and more as you put the lane cover over 65% which can be extremley distracting at times.
 
**To Reproduce**
1. Go to 'Options'
2. Click on 'Gameplay'
3. Scroll down to 'Lane Cover'
4. Enable 'Bottom Lane Cover'
5. Go anywhere above 65% on bottom lane cover
6. Play any map, preferebly 4k maps
7. Look at the bottom

**Expected behavior**

I expected the lane cover to cover anything from bottom to top no matter how high the lane cover might be.

**Screenshots**
![Bildschirmfoto von 2021-10-06 19-40-51](https://user-images.githubusercontent.com/92050183/136255542-2fba2bca-3ac0-418b-9522-4dc71d35166d.png)
![Bildschirmfoto von 2021-10-06 19-40-57](https://user-images.githubusercontent.com/92050183/136255644-aa1cd31b-6769-4a19-81b8-270c481e0491.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Browser Chrome, Firefox
 - Version 21.04

**Additional context**
I use 1920x1080 Res 144fps. I use linux

**Comment by Illuminati-CRAZ** [comment] 2021-10-06 18:05
duplicate of #2303

**Closed by Illuminati-CRAZ** 2021-10-06 18:05 UTC
