### ISSUE TITLE
Adjusting note size per column

### ISSUE THREAD

**Issue by Connormgs** [Quaver/Quaver#1945] opened 2020-05-08 19:28 UTC
**Is your feature request related to a problem? Please describe.**
Some games like o2jam have note graphics on buttons 2 and 6 for example that aren't as wide as all the others, button 4 being the widest of all of them, right now all the notes are the same width. 
**Describe the solution you'd like**
The ability to adjust the height/width of note graphics in skin.ini without having to edit the graphics directly. Osumania lets you adjust note height from the .ini for example. 
**Describe alternatives you've considered**
None. 

**Additional context**
It would make adjusting skins way easier.

**Comment by Swan** [comment] 2020-11-25 20:31
Duplicate of #1400

**Closed by Swan** 2020-11-25 20:31 UTC
Labels: Skinning
