### ISSUE TITLE
Cursor dissapears when test playing in the editor without any hitobjects

### ISSUE THREAD

**Issue by lilxleb** [Quaver/Quaver#2296] opened 2020-07-11 18:08 UTC
**Describe the bug**
Cursor dissapears when test playing in the editor without any hitobjects

**To Reproduce**
1. Import a song
2. Add metadata (to get to the editor)
3. Make one timing point
4. Place a few (dont know if this triggers with only one object placed) objects
5. Scroll until the blue bar (https://prnt.sc/tfzoot) is past the hit objects
6. Press the Test play button

**Expected behavior**
Error should pop up (does) but the cursor needs to remain visible

**Comment by Swan** [comment] 2020-07-11 18:55
Duplicate of https://github.com/Quaver/Quaver/issues/1908

**Closed by Swan** 2020-07-11 18:55 UTC
