### ISSUE TITLE
Game starts up and load things very slowly when having network problems

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#2488] opened 2020-07-27 05:32 UTC
[network.log](https://github.com/Quaver/Quaver/files/4980085/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/4980086/runtime.log)

There was a brief period of time when Steam servers had some downtime when I tried to open Quaver, but it stopped and I still can't load the game at a normal speed. It seems to have taken 17 minutes to fetch and load my Steam avatar, took another 1.5 minutes loading the main menu, and 3 minutes to get to song select.

**Comment by Swan** [comment] 2020-07-27 13:14
Duplicate of/Related to #1158

**Closed by Swan** 2020-07-27 13:14 UTC
