### ISSUE TITLE
Black screen upon opening map

### ISSUE THREAD

**Issue by Doksha** [Quaver/Quaver#3940] opened 2023-12-11 20:33 UTC
### Describe the bug

Any time I open a map, it just shows a black screen, it is impossible to exit this, the only way to get out of this is alt F4
This was not an issue yesterday, and nothing has changed since then (except I am now offline)
I have tried changing between fullscreen and windowed and changing resolutions, none of which have fixed the issue

The only way I can find to play maps is to enter them in the editor and select test map.

### To Reproduce

1. open quaver
2. go to single player
3. enter any map

### Expected behavior

map should load

### Log Files

[network.log](https://github.com/Quaver/Quaver/files/13640647/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/13640648/runtime.log)

**Comment by Warp9000** [comment] 2023-12-11 20:47
duplicate of #3917 and has been fixed in #3924

**Closed by Warp9000** 2023-12-11 20:47 UTC
Labels: Bug
