### ISSUE TITLE
Map upload with no audio

### ISSUE THREAD

**Issue by CordingWater6** [Quaver/Quaver#2966] opened 2021-05-02 21:27 UTC
**Describe the bug**
I uploaded a map to the Quaver website, and despite it needing audio to go there, the map has none at all. And so (despite me making the map with sync to audio) the map was forced to be unranked and rejected because of this error outside of my control.

**To Reproduce**
Steps to reproduce the behaviour:
1 - Make a map (MacOS)
2 - Upload it to the server (doesn't matter if the map is rankable or not)
3 - Error will appear when playing the map back

**Expected behaviour**
You should be able to play the audio preview and hear the song, as well as download it with the audio. 

**Screenshots**
I have no screenshots of this error. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome
 - Version: 0.28.0

**Additional context**
I hope this doesn't happen again, considering how I'm working on another map and would hate for it to have this same issue, proving that all the time I've spent on the map was not worth it at all.

**Comment by Emptiest** [comment] 2021-05-02 21:50
Check your mp3 file for any non-romanized characters in either the filename or the metadata. Quaver no like non-romanized characters.

**Comment by Emptiest** [comment] 2021-05-02 21:58
Once you change the name of the mp3 file, make sure you also change the reference in your map file (.qua).

e.g. if you renamed the file to audio.mp3, then the first line of the .qua should be as follows:
`AudioFile: audio.mp3`

If you have any further issues with this I'd recommend asking questions in the #mapping channel on the official discord.

**Comment by Illuminati-CRAZ** [comment] 2021-05-09 00:27
Probably duplicate of #2325

Your mapset was denied because it was apparent, even without the audio file, that it wasn't worthy of being ranked.

**Closed by Illuminati-CRAZ** 2021-05-09 00:27 UTC
