### ISSUE TITLE
ALT GR button does not get mapped correctly (UK layout keyboard)

### ISSUE THREAD

**Issue by thomasdayman** [Quaver/Quaver#2796] opened 2020-12-28 16:14 UTC
Mapping the ALT GR gets mapped as 2 buttons (LCTRL RALT)
![Screenshot_1](https://user-images.githubusercontent.com/74782947/103227930-8347b900-4927-11eb-9cbf-0b2a27c270d1.png)

**Comment by Swan** [comment] 2021-01-01 18:37
Duplicate of #858

**Closed by Swan** 2021-01-01 18:37 UTC
