### ISSUE TITLE
Allow proper navigation of text boxes

### ISSUE THREAD

**Issue by Cuckson** [Quaver/Quaver#3338] opened 2021-12-20 11:02 UTC
**Is your feature request related to a problem? Please describe.**
I am annoyed at the fact that I have to delete text to enter new text, as currently you cannot move through text with arrow keys or click to a different part of the text. This problem is most prevalent when changing tags in a mapsets metadata, for example if I have 20 keywords in my tags and I need to delete keyword entry 1, I have to delete all 19 to remove that one. This is also a problem for regular players who use the chat system, as you have to backspace to fix a spelling issue if you make one somewhere for example. For pretty much any other text box in the game this is a problem that exists.

There are of course workarounds but I am proposing a cleaner, proper solution to the problem.

**Describe the solution you'd like**
I would like to be able to use arrow keys or any other suitable keybind to move through text, or the ability to click on an area of the text and the text box cursor will move to that position. This should solve all the prior problems mentioned.

**Comment by Illuminati-CRAZ** [comment] 2021-12-20 11:29
duplicate of https://github.com/Quaver/Wobble/issues/6

**Closed by Illuminati-CRAZ** 2021-12-20 11:29 UTC
