### ISSUE TITLE
[EDITOR] Editor should open into the song list when selected from main menu.

### ISSUE THREAD

**Issue by Reyder95** [Quaver/Quaver#598] opened 2019-02-23 20:31 UTC
As the title states, I don't think many people will be editing the song that comes up out of random. You can edit from the song list itself but imo you should be able to choose the song from the main menu editor too.

**Comment by Swan** [comment] 2020-04-06 15:20
Closing as this is intended behavior. If you want to edit a specific song, you can do it from the actual song select screen.

**Closed by Swan** 2020-04-06 15:20 UTC
Labels: Editor, Main Menu
