### ISSUE TITLE
More Advanced Map Selection Filtering, Draggable Scroll Bar

### ISSUE THREAD

**Issue by grimnoiir** [Quaver/Quaver#3359] opened 2022-01-15 02:11 UTC
When you have a large map pool (at 3500+ currently), finding the maps you want to play can be really tedious because of the lack of filtering options and draggable scroll bar. The two big filters for me are showing only ranked maps, and only showing maps within a certain difficulty range. 

If I only want to play ranked maps within my skill range atm, the only feasible way of doing it is to scroll through hundreds of maps to get to my difficulty level, and then mentally filtering out unranked maps.

I suggest adding an 'only ranked maps' tickbox on the map selection screen, a 'shown difficulty range' slider in the options menu, and making the visual scroll slider draggable so you jump down the list quickly instead of needing to manually scroll.

**Comment by Illuminati-CRAZ** [comment] 2022-01-15 02:56
See [this](https://wiki.quavergame.com/docs/faq#how-do-song-select-search-filters-work?) for more advanced search filters

Draggable scroll bar suggestion is a duplicate of #2102, and you can press and hold the middle mouse button to jump through the list quickly

**Closed by Illuminati-CRAZ** 2022-01-15 02:56 UTC
