### ISSUE TITLE
[redesign] "Are you sure you would like to quit the game? (CREATE)/(CANCEL)"

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#1169] opened 2019-10-21 19:53 UTC
**Describe the bug**
Refer to title or image. Should say "Yes" or "Quit Game" instead or not?

![20191021215132_1](https://user-images.githubusercontent.com/22303902/67238252-244a0280-f44d-11e9-8e54-f4bcadf2300e.jpg)

**Comment by YaLTeR** [comment] 2019-10-21 19:55
duplicate of https://github.com/Quaver/Quaver/issues/1147

**Closed by YaLTeR** 2019-10-21 19:55 UTC
