### ISSUE TITLE
Sound plays in computer not headphones

### ISSUE THREAD

**Issue by TryHardGamerYT** [Quaver/Quaver#2585] opened 2020-08-23 02:54 UTC
I plugged in my headphones so I don't distract my family while I make my map but the sound still plays from the computer. I think it might be my headphones because they are a bit old and worn out and broken but I check the computer first and it says sound is playing from the headphones so I play a yt video and sound comes from the headphones.

1. Plug in headphones, play game.

 Windows 10
Brave

**Comment by Swan** [comment] 2020-08-25 13:35
Quaver currently uses the default audio device to play sound.

Related to/duplicate of #569

**Closed by Swan** 2020-08-25 13:35 UTC
