### ISSUE TITLE
Option to have custom time signatures

### ISSUE THREAD

**Issue by lilxleb** [Quaver/Quaver#2271] opened 2020-07-10 21:10 UTC
For example, if a map has a whole load of time signature changes from 3/4 to 4/4 to 5/4 and so on, it might be and is frustrating to map, since you have to remember at every timing point to change the beat snap. A suggestion might be to just use the 3/4ths timing snapper, but that will become inaccurate if it is anything other than 3/4. Good example for the implementation would be osu!

**Comment by Swan** [comment] 2020-07-11 13:05
Duplicate of #602

**Closed by Swan** 2020-07-11 13:05 UTC
