### ISSUE TITLE
Map background not showing up during gameplay

### ISSUE THREAD

**Issue by robby250** [Quaver/Quaver#1993] opened 2020-05-17 15:20 UTC
Don't know if this was caused by an update or something I did, but the song background doesn't show up anymore during gameplay for any map, instead I get the default quaver background:
![5172020 14-26-3-450](https://user-images.githubusercontent.com/51453670/82152603-091c6580-986b-11ea-9fa9-eff551380e65.jpg)

**Comment by Swan** [comment] 2020-05-17 16:35
Duplicate of #1166

**Closed by Swan** 2020-05-17 16:35 UTC
