### ISSUE TITLE
No release timing mod

### ISSUE THREAD

**Issue by citrus3301** [Quaver/Quaver#3333] opened 2021-12-16 14:53 UTC
Is your feature request related to a problem? Please describe.
A lot of SM/Etterna players dont really like playing quaver since there is release timings, I think adding even an unranked mod to remove the release timings would be a good idea and would help more people to enjoy the game. Additionally this would make playing etterna maps which have long notes not made for release timings more fun. We already have a no LN mod so why a no RT mod?

Describe the solution you'd like
Add a mod that only checks that you hit the start of a long note, and makes sure you hold it all the way through, but doesn't care when you release it after you've held the entire note, it doesn't give you a marvelous for holding the entire note, it just avoids giving your a miss. Obviously unranked like no LN, but still it would be fun.

Alternatives:
For an alternative i think you could also make it so that releasing early gives you a bad/good not a miss as to not break combo, but either way I think the mod overall would be good

**Comment by citrus3301** [comment] 2021-12-16 14:56
For an alternative i think you could also make it so that releasing early gives you a bad not a miss as to not break combo, but either way I think the mod overall would be good

**Comment by citrus3301** [comment] 2021-12-16 14:58
it could be a bad or a good tbh

**Comment by Swan** [comment] 2021-12-16 19:40
Please use the search function before opening up an issue. It's a duplicate of #2429.

**Closed** 2021-12-16 19:40 UTC

**Comment by citrus3301** [comment] 2021-12-16 20:06
> Please use the search function before opening up an issue. It's a duplicate of #2429.

It's not a duplicate of that request, that request is asking for an entire new note type to be added for charters to use while stating it specifically does not want it to be a toggleable mod. I am suggesting the opposite as I want a togglable mod in order to automatically turn off release timings on imported etterna/sm maps as to play them with engine functions as originally intended, only adding the new note type and not the mod I proposed would require players to go and edit each etterna import they want to remove release timings from manually which would be very frustrating. While I have no opinions on whether a new note type gets added, my request is specifically asking for a mod that the other requests not be added which is why I do not believe this is a duplicate.

**Comment by Swan** [comment] 2021-12-16 20:12
Discussion can go there then. No point in a separate issue.
