### ISSUE TITLE
Calling map preview ans player's stats screens at the same time.

### ISSUE THREAD

**Issue by conslab** [Quaver/Quaver#3489] opened 2022-06-07 06:56 UTC
**Describe the bug**
Map preview is overlapped by player's stats if calling it at the same time.
If repeat, there is no Leaderboard panel info on the left.

**To Reproduce**
1. Go to the map selecting screen.
2. Press F3 and F4 at the same time.
3. Map preview can't be seen because of player's stats. (BUG)
4. Press F3 and F4 at the same time again.
5. Nothing is shown at the left. (BUG)

**Expected behavior**
The panel on the left showing map preview OR player's stats, but not both at the same time.
The Leaderboard panel should be shown if nothing else is there.

**Screenshots**

Map preview and player's stats is showing at the same time.
![preview-and-stats](https://user-images.githubusercontent.com/80941899/172314833-9feb04a7-9143-4cff-965d-3f1408cd5151.jpg)

Empty panel on the left
![empty](https://user-images.githubusercontent.com/80941899/172314848-53548ff4-b8e3-4c14-b423-3b070b9b6319.jpg)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 101.0
 - Version: Steam's latest

**Comment by Illuminati-CRAZ** [comment] 2022-06-07 07:00
Duplicate of #1603

**Closed by Illuminati-CRAZ** 2022-06-07 07:00 UTC
