### ISSUE TITLE
Difficulties name of mapsets are wrongly sorted by alphabetical order when hovering over in map search.

### ISSUE THREAD

**Issue by 5h1zuy4** [Quaver/Quaver#3012] opened 2021-05-18 02:23 UTC
![5182021 12-14-12-513](https://user-images.githubusercontent.com/82523959/118580491-4cd5e200-b7d3-11eb-85bb-ca42ee0d31b8.jpg)

**Comment by Kizuna-dev** [comment] 2021-05-18 03:29
It's because they are not sorted alphabetically, but in difficulty rating, look in your screenshot, from top to bottom, it goes from a beginner to an extra, a map rated "1.28" to "28.49". This sorting is intended.

**Comment by Illuminati-CRAZ** [comment] 2021-05-22 06:34
duplicate of #2539

**Closed by Illuminati-CRAZ** 2021-05-22 06:34 UTC
