### ISSUE TITLE
Stutter and hit window shifting

### ISSUE THREAD

**Issue by grumpybutter** [Quaver/Quaver#484] opened 2019-01-07 04:29 UTC
**Describe the bug**
Every so often, often near the beginning of the map, the game will lag/stutter/freeze and this will cause the hit window to shift later and later.

**To Reproduce**
1. Start a map
2. Wait for stutter
3. The hit window timing shifts

**Screenshots**
![quaver_2019-01-06_21-05-39](https://user-images.githubusercontent.com/24850504/50749111-c2e0dc00-120a-11e9-9a77-a3a82893cee7.png)
![quaver_2019-01-06_23-17-42](https://user-images.githubusercontent.com/24850504/50749117-cb391700-120a-11e9-9461-30b6fa5a2588.png)

**Desktop**
 - OS: Windows 10 Education 64 bit
 - GPU: GTX 960
 - CPU: i5 4460
 - RAM: 8 GB

**Comment by Swan** [comment] 2019-01-23 13:50
Duplicate of #359

**Closed by Swan** 2019-01-23 13:50 UTC
Labels: bug, fps drop, gameplay
