### ISSUE TITLE
Ö Ä # (and) Ü on an qwertz keyboard register as "none" in the 4k and 7k layout screen

### ISSUE THREAD

**Issue by christusautistus** [Quaver/Quaver#886] opened 2019-07-01 18:37 UTC
**Describe the bug**
Trying to use the Ö Ä # (and) Ü Buttons on and qwertz keyboard on the 4k and 7k layout result as "None" and when one of them is pressed while 2 or more of them are "None" results in every Line assigned to "None" to be pressed.

**To Reproduce**
1. Go to Options - Input - Gameplay Layout (4 Keys) [or/and 7 Keys] 
2. Click on Change and pressing the described Buttons should result to showing ``None´´
3. All ingame Lines assigned to "None" react if only one correspondending Button is pressed

**Expected behavior**
Ö Ä # and Ü should show up in the layout screen as there correspondending Buttons and ingame work as seperate Buttons when pressed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Keyboard:Klim Domination (https://de.store.klimtechs.com/products/klim-domination)

**Comment by Swan** [comment] 2020-11-25 19:30
Duplicate of #858

**Closed by Swan** 2020-11-25 19:30 UTC
Labels: Requires Wobble
