### ISSUE TITLE
Dan courses/level player's skill

### ISSUE THREAD

**Issue by aphelionosu** [Quaver/Quaver#2486] opened 2020-07-26 16:18 UTC
Since this game can disable score submission when pausing, I guess it will be great to add player level skill or also known as Dan courses, where player should clear numbers of charts/maps with some condition such as accuracy, judgement, etc to be counted as cleared a dan . This feature already available in some games such as LR2, SM, SDVX, etc and I guess it is good to be added to the game

Dan courses charts/maps shouldn't be ranked so it doesn't increase the rank but still reward the player as achievement, profile badge, or anything that make it visible to other player in leaderboard, online users, and/or chat. Those charts also can be made by staffs. You might want to recruit more staff for this stuff (no pun intended)

**Comment by qusteka** [comment] 2020-07-26 16:37
Dans are already conceptually planned and implemented partially.

**Comment by Swan** [comment] 2020-07-27 13:12
Duplicate of #603

**Closed by Swan** 2020-07-27 13:12 UTC
