### ISSUE TITLE
Editor Does Not Reflect 3/4 Time Signature

### ISSUE THREAD

**Issue by Illuminati-CRAZ** [Quaver/Quaver#2019] opened 2020-05-21 07:26 UTC
Although .qua files support non 4/4 time signatures, the editor denotes a new measure every 4 beats instead of every 3 for 3/4. I assume this is also the case for other non 4/4 time signatures.

**Comment by Swan** [comment] 2020-07-11 13:05
Duplicate of #602

**Closed by Swan** 2020-07-11 13:05 UTC
Labels: Editor
