### ISSUE TITLE
Allow player to see score/ratio without clicking on the person's score to take them to their score page

### ISSUE THREAD

**Issue by xKibitz** [Quaver/Quaver#2462] opened 2020-07-24 11:37 UTC
The title might seem a bit difficult to understand but basically it's a feature in osu where you hover your cursor over the score you want to see their ratio for example to see how much acc you need to beat them instead of taking extra time to click on the person's score and go their score page and exit back out. It may be a small feature but it's time saving :3 

example if i want to hover over the score
![image](https://user-images.githubusercontent.com/67725177/88387375-6b16bf80-ce06-11ea-807d-864db118f407.png)
![image](https://user-images.githubusercontent.com/67725177/88387462-94cfe680-ce06-11ea-9c56-78ba46a9cebe.png)

**Comment by Swan** [comment] 2020-07-25 14:19
Duplicate of #2196

**Closed by Swan** 2020-07-25 14:19 UTC
