### ISSUE TITLE
Different Column Widths

### ISSUE THREAD

**Issue by 10ai** [Quaver/Quaver#3721] opened 2022-12-29 16:35 UTC
Currently it is possible to have custom column widths by using skinning tricks involving negative padding and transparency but this is quite annoying to do and can be finicky. It would be best if you could specify multiple widths in skin.ini.
Possibly:
```yaml
ColumnSize1: 40
ColumnSize2: 30
ColumnSize3: 40
ColumnSize4: 50
ColumnSize5: 40
ColumnSize6: 30
ColumnSize7: 40
```

**Comment by Swan** [comment] 2023-01-15 15:44
Duplicate of #1400

**Closed by Swan** 2023-01-15 15:44 UTC
