### ISSUE TITLE
Zoomed in Windows glitches the game

### ISSUE THREAD

**Issue by esqzerolol** [Quaver/Quaver#2313] opened 2020-07-12 01:53 UTC
**Describe the bug**
I Have a Ultrawide monitor, to make icons a little bigger i have to put zoom in windows (see picture)
and this appears to make the game go crazy about the resolution.

**To Reproduce**
Just have a Ultrawide monitor and apply windows zoom
In-game you have to put the game on full screen and the glitch is good to go
(I think this problem extend to normal FullHD, but I'm unsure)

**Expected behavior**
The screen will be zoomed in like this https://prnt.sc/tg51yp (The screenshot is a little TOO zoomed from the intended bug because lightshot seems to be glitching it a little more)

**Screenshots**
Going to place the links again
https://prnt.sc/tg514n
https://prnt.sc/tg51yp (this is how the game looks like, i'm not cutting anything from the print)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: I don't know

**Other glitch involving same thing**
The game also appears to lose quality in windowed mode with this option, i will link 2 screenshots comparing:
https://prnt.sc/tg55v7 (This is with the 125% game looks like)
https://prnt.sc/tg5615 (This is the game with 100% zoom (default zoom in windows) looks like)

**Comment by Swan** [comment] 2020-07-12 15:08
Duplicate of https://github.com/Quaver/Quaver/issues/362

**Closed by Swan** 2020-07-12 15:08 UTC
