### ISSUE TITLE
[Downloading maps] No song is played while clicking on maps Linux

### ISSUE THREAD

**Issue by Pebor** [Quaver/Quaver#2586] opened 2020-08-23 05:53 UTC
When am downloading songs from the game it self, I don't hear any preview music playing.

 - OS: [Ubuntu 20.04]

**Comment by Swan** [comment] 2020-08-25 13:35
Duplicate of #2578

**Closed by Swan** 2020-08-25 13:35 UTC

**Comment by 0e4ef622** [comment] 2020-08-28 14:37
I don't know why this was marked as a duplicate, #2578 states they have no audio anywhere, but this issue is specific to downloading maps. I also had this same issue on Arch Linux, no download previews but audio every else works. Here's a possibly useful snippet from `network.log`

```
[7:26:56] - NETWORK - ERROR: Wobble.Audio.AudioEngineException: Cannot call AfterLoad if stream isn't loaded.
   at Wobble.Audio.Tracks.AudioTrack.AfterLoad()
   at Wobble.Audio.Tracks.AudioTrack..ctor(Uri uri, Boolean preview, Boolean autoDispose)
   at Quaver.Shared.Screens.Downloading.DownloadingScreen.<>c__DisplayClass148_0.<<LoadAudioPreview>b__0>d.MoveNext()
```

**Comment by Ricky12Awesome** [comment] 2022-05-24 11:14
I have the same exact issue

as you can hear, audio works elsewhere, just not when downloading maps

https://user-images.githubusercontent.com/29931568/170021296-6f0a0110-cae8-4168-91e7-1ef0ae8bc412.mp4

log: [network.log](https://github.com/Quaver/Quaver/files/8762072/network.log)
