### ISSUE TITLE
Skin Editor ?

### ISSUE THREAD

**Issue by Edouardo26** [Quaver/Quaver#2266] opened 2020-07-10 17:51 UTC
Hello, if a skin editor (even very simple it's okay)can be added it would be really useful for me (I really don't understand anything to all these **_wow skin.iniiiii_**) as much as for other people who... Like me don't understand anything... . Maybe make an in-game skin editor where you can for exemple ajust directly the size and emplacement of images or make an element transparent. Thanks. (Sorry if I don't have a god-like english)

**Comment by YaLTeR** [comment] 2020-07-10 17:52
Duplicate of #344

**Closed by YaLTeR** 2020-07-10 17:52 UTC
Labels: Duplicate
