### ISSUE TITLE
Option to change render order of hitnotes

### ISSUE THREAD

**Issue by Prankster855** [Quaver/Quaver#2367] opened 2020-07-14 06:26 UTC
Currently, newer hit notes are rendered below the older ones, Which may or may not cause some issues with skins, or the creator has a preference for when hit notes stack.

**Describe the solution you'd like**
A boolean in skin.ini that makes newer notes render above older ones and vice-versa.

**Newer Notes** as in the preceding notes

**Comment by Swan** [comment] 2020-07-14 15:06
Duplicate of #2298

**Closed by Swan** 2020-07-14 15:06 UTC
