### ISSUE TITLE
Autoplay / replay misses or loses accuracy

### ISSUE THREAD

**Issue by Luftii** [Quaver/Quaver#502] opened 2019-01-13 22:44 UTC
**Describe the bug**
When doing anything such as holding down the left mouse button on the Quaver window border, pressing Alt + Tab or doing any other action that makes the game lose focus, it will miss / lose accuracy.

**To Reproduce**
1. Play a map with Autoplay mod or watch a replay

*For fullscreen:*

2. Press Alt + Tab to switch to another window / program

*For windowed:*

2. Hold down left mouse button on window border

3. Autoplay / replay will miss or lose accuracy

**Expected behavior**
Autoplay and replays should not be affected by this.

**Screenshots**
https://i.imgur.com/4Hh4B2p.png

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Swan** [comment] 2019-01-23 13:49
Duplicate of #341

**Closed by Swan** 2019-01-23 13:49 UTC
Labels: Replays, bug, gameplay
