### ISSUE TITLE
Changing Audio Device Breaks Audio and Play Button

### ISSUE THREAD

**Issue by ChristopherGirard** [Quaver/Quaver#2304] opened 2020-07-11 22:18 UTC
When the user turns off their headset and changes their audio device for their monitor, they can no longer use the jukebox play button at the bottom of the main menu, it won't respond nor change to the "Pause" icon. 

They will have to restart the application as well if they want to hear anything after changing audio device.

**Comment by staravia** [comment] 2020-07-11 23:45
Duplicate of https://github.com/Quaver/Quaver/issues/569

**Closed by staravia** 2020-07-11 23:45 UTC
Labels: Enhancement, New Feature
