### ISSUE TITLE
Lower part of the screen cannot be clicked when on borderless fullscreen.

### ISSUE THREAD

**Issue by ToshiyukiDoma** [Quaver/Quaver#2277] opened 2020-07-11 05:07 UTC
**Describe the bug**
Lower part of the screen cannot be clicked when on borderless fullscreen.

**To Reproduce**
Just enable borderless fullscreen.

**Expected behavior**
You will be clicked away from the game.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: N/A

**Additional context**
It's nothing much but some players do prefer playing in borderless fullscreen. Would be nice if this can be fixed.

**Comment by Swan** [comment] 2020-07-11 13:01
Most likely a duplicate of #362. Can be solved by turning down windows scaling

**Closed by Swan** 2020-07-11 13:01 UTC
