### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by lazichicken123** [Quaver/Quaver#2459] opened 2020-07-23 00:39 UTC
**Describe the bug**
Sound stops after switching sound source in windows setting

**To Reproduce**
1. click on volume icon in windows 10 
2. click the playback device and change to a device
3. The sound will not be be able to be played without restarting the game

**Expected behavior**
I expect the sound to be able to be played when switching to a different playback device

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Steam
 - Version 0.20.0
**Additional context**

**Comment by Swan** [comment] 2020-07-25 14:17
Duplicate of https://github.com/Quaver/Quaver/issues/569

**Closed by Swan** 2020-07-25 14:17 UTC
