### ISSUE TITLE
Add an option to change your audio driver

### ISSUE THREAD

**Issue by MRePotatoes** [Quaver/Quaver#2268] opened 2020-07-10 18:58 UTC
I use Voicemeeter Banana as my main audio driver to have proper control over my audio in and out. Simple problem: it adds delay to the audio, and the audio offset option can't fix the hitsound delay, which is frustrating.
I usually change the audio out driver for certain games or software to my actual audio driver when I need to, but Quaver doesn't have that option!

Please add that option, as it's basically impossible to play the game w/ delay this big.

**Comment by YaLTeR** [comment] 2020-07-10 18:59
Duplicate of #2259

**Closed by YaLTeR** 2020-07-10 18:59 UTC
