### ISSUE TITLE
Arrow Navigation for Keymode Search in Song Selection Not Responding normally

### ISSUE THREAD

**Issue by KaidenFrizu** [Quaver/Quaver#957] opened 2019-07-20 08:09 UTC
**Describe the bug**
Arrow navigation during song select specifically navigating with key search option fails to respond normally.

**To Reproduce**
1. Go to Song Select
2. Input on search box "keys=4" or "keys=7". Notice that the maps appeared only for the specific keymode.
3. Select a song that contains 4 or more maps. Make sure to select using the arrow keys and press enter.
4. Use the arrow keys left and right to navigate through the difficulties.
5. After some left and right clicks, the arrow keys function stopped working but the mouse navigation works fine.

**Expected behavior**
Arrow navigation should work normally and should not stop working during keymode search.

**Desktop**
 - OS: Windows 8
 - Version 0.16.0

**Comment by YaLTeR** [comment] 2019-07-20 19:36
Duplicate of https://github.com/Quaver/Quaver/issues/745.

**Closed by YaLTeR** 2019-07-20 19:36 UTC
