### ISSUE TITLE
Audio not working, Radio in home menu having a spasm

### ISSUE THREAD

**Issue by OyasumiPurple** [Quaver/Quaver#3226] opened 2021-08-29 22:24 UTC
The bug im having:
This is the first time im ever playing quaver, and i played 2 maps today, after the second map, the audio suddenly stopped working, not on my PC side, as everything else had audio, just the game, and all of the radio songs in the home menu was in negative time frames, like -2:15, making all of the songs get skipped over eachother again and again, basically making them spasm in the menu.

I dont have a true way to REPRODUCE this behaviour, but this explanation should be more precise:
I opened Quaver, logged in, and put on a skin.
I played 2 maps, and in between them i set my callibration.
After the 2 maps were played, i set my game to fullscreen because i forgot to earlier.
The bug started to happen.

Expected behavior of this bug is to have your radio skip songs super fast, and absolutely no audio working at all during the game, logged in or not, settings changes will not work.

I do not have any screenshots as this is an audio bug, although the radio having a spasm might be able to be captured, i do not know how to upload videos here.

OS: Windows 10
Browser: Chrome
Version: (i seriously dont know)

No additional context, i stared playing quaver TODAY, like an HOUR before this bug was reported by me, so i honestly have no clue what happened if im going to be completely honest.

**Comment by Swan** [comment] 2021-11-15 14:54
This is due to either outdated audio drivers, your audio device changing, or your audio device not being the default.
Duplicate of #569

**Closed by Swan** 2021-11-15 14:54 UTC
