### ISSUE TITLE
Game Lagging/Freezing when mass-selecting in Editor

### ISSUE THREAD

**Issue by Cuckson** [Quaver/Quaver#3124] opened 2021-07-20 08:49 UTC
**Describe the bug**
When you drag your cursor large amounts using the select tool (scrolling vertically) it will cause the game to freeze and frame drop consistently until you stop selecting.

**To Reproduce**
1. Go to the Editor by selecting a Song
2. Mass Select the notes with the Select Tool by dragging your cursor (not CTRL+A)

**Expected behavior**
Select objects and selecting in general in the Editor without my game dropping frames / freezing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Game Version [0.29.0] (Canary Build)
 - OS Version [19042.1052]

**Additional context**
This bug has only happened to me on the new Canary Build of the game.
This will still happen by just dragging the select tool upwards or downwards, not even selecting notes.

**Comment by Cuckson** [comment] 2021-07-20 09:01
Seems like this issue is tied to a single map I have, but still an issue that is unresolved.

**Comment by Cuckson** [comment] 2021-07-21 23:43
Mocking this up to be an issue only I have on one specific map, and will close the issue.

**Comment by Jolomann** [comment] 2021-07-30 21:45
reopen this b https://streamable.com/wyecby

**Comment by Illuminati-CRAZ** [comment] 2021-08-07 22:16
Duplicate of #1821

**Closed by Illuminati-CRAZ** 2021-08-07 22:16 UTC
