### ISSUE TITLE
Config file data loss

### ISSUE THREAD

**Issue by YaLTeR** [Quaver/Quaver#421] opened 2018-12-29 21:58 UTC
**Describe the bug**
The way Quaver handles `quaver.cfg` (and possibly other files) may result in data loss. I was launching Quaver while my drive was running out of space, and I ended up with my `quaver.cfg` completely cleared by Quaver. I suspect this is due to it overwriting the file naively as opposed to doing a more clever scheme (writing a temporary file and moving it over), which failed due to lack of disk space. However it's also odd that Quaver needed to write the config file at all since nothing has changed in it since the last time I launched the game.

Arch Linux x64

**Comment by Swan** [comment] 2019-01-23 14:09
Duplicate of #247

**Closed by Swan** 2019-01-23 14:09 UTC
Labels: bug, config
