### ISSUE TITLE
[Song Select] Truncate difficulty name instead of rate and judgement preset

### ISSUE THREAD

**Issue by Jolomann** [Quaver/Quaver#2427] opened 2020-07-18 23:30 UTC
**Is your feature request related to a problem? Please describe.**
On long difficulty names, the string for `difficulty name  + rate + judgement preset` gets truncated, hiding judgement preset and rate

**Describe the solution you'd like**
 I suggest only truncating the difficulty name instead of the whole line, in order to keep the judgement preset and rate visible

Now:
![now](https://bries.s-ul.eu/Mw0Gv4MD.png)

Suggestion:
![suggestion](https://cdn.discordapp.com/attachments/461621899320098816/734189928786952252/unknown.png)

**Comment by Swan** [comment] 2020-07-20 15:33
Duplicate of #1598

**Closed by Swan** 2020-07-20 15:33 UTC
