### ISSUE TITLE
Can't disable chat inputs while playing on Multiplayer map preview

### ISSUE THREAD

**Issue by Hekirekigami** [Quaver/Quaver#3838] opened 2023-08-04 17:31 UTC
Before, you could click somewhere else on screen and text cursor would disappear, then play the map in"View map" without all the inputs showing up in the chat.

now chat can't be disabled.

 - Windows 11
 - Chrome

**Comment by AiAe** [comment] 2023-08-07 13:49
Duplicate of https://github.com/Quaver/Quaver/issues/2064

**Closed by AiAe** 2023-08-07 13:49 UTC
Labels: Multiplayer
