### ISSUE TITLE
Universal keyboard support

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#401] opened 2018-12-28 01:55 UTC
You could use FNA (looks very related to XNA) for converting keycodes and supporting all keyboards with minimal effort.

If you tell me where you handle all the keyscans i'll try to implement it but i'm not sure i will be able to, since it might be an extension to XNA and i don't really want to meddle with structure.

https://github.com/FNA-XNA/FNA/wiki/5:-FNA-Extensions#getkeyfromscancodeext

**Comment by Swan** [comment] 2019-01-23 14:03
Duplicate of #297

**Closed by Swan** 2019-01-23 14:03 UTC
Labels: Input, Requires Wobble
