### ISSUE TITLE
Editor UI issues

### ISSUE THREAD

**Issue by ThatOneN3rd** [Quaver/Quaver#3602] opened 2022-08-20 02:13 UTC
**Describe the bug**
The dropdown menus in the editor appear behind the UI elements

**To Reproduce**
1. Open editor
2. Click on dropdown menu

**Expected behavior**
Dropdown menu should be on the top layer 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 
 - Version 1.0

![8192022 18-57-58-232](https://user-images.githubusercontent.com/111621145/185725307-b08a31f5-b20d-4310-8868-5cfbfb92214f.jpg)

**Comment by chirijidev** [comment] 2022-08-20 02:21
I checked this error and at first, nothing's really wrong in my editor when I first opened it.
![8202022 10-17-41-907](https://user-images.githubusercontent.com/55966752/185725454-69801fd7-1de2-4425-8717-f0d1052d7eca.jpg)

But when I open the **Display Game Preview/Reference Difficulty** back on, this happens:
![8202022 10-19-13-145](https://user-images.githubusercontent.com/55966752/185725471-b718b01c-69fc-46de-a0a8-d9cdbf0204be.jpg)
![8202022 10-20-20-888](https://user-images.githubusercontent.com/55966752/185725505-534a30a0-02b2-4bde-b90c-5a734de8577c.jpg)


Disabling it doesn't seem to solve the problem.
![8202022 10-19-35-354](https://user-images.githubusercontent.com/55966752/185725481-44bf2021-e783-4a08-a12f-61f1ca26feea.jpg)

**Comment by AiAe** [comment] 2022-08-20 10:31
Duplicate of https://github.com/Quaver/Quaver/issues/3582 please search before making issues.

**Closed by AiAe** 2022-08-20 10:31 UTC
