### ISSUE TITLE
Lag spikes and sudden game crash.

### ISSUE THREAD

**Issue by Supbads** [Quaver/Quaver#365] opened 2018-12-24 14:01 UTC
Pretty self explanatory.

I am having minor lag spikes every 5-10 seconds while in a file.
Game ver: Quaver v0.11.0
OS: Windows 10 64x
Attached logs for analyzing the crash:
[network.log](https://github.com/Quaver/Quaver/files/2707388/network.log)
[runtime.log](https://github.com/Quaver/Quaver/files/2707389/runtime.log)

**Comment by Swan** [comment] 2018-12-24 14:32
@Supbads Can you post your PC specs?

**Comment by Supbads** [comment] 2018-12-24 14:34
Ofcourse.
https://i.imgur.com/1WJXUr7.png

**Comment by Swan** [comment] 2019-01-23 13:57
Duplicate of #359

**Closed by Swan** 2019-01-23 13:57 UTC
Labels: bug, fps drop, game crash, gameplay
