### ISSUE TITLE
Misaligned Alert text on "Chat" in Offline Mode

### ISSUE THREAD

**Issue by KaidenFrizu** [Quaver/Quaver#937] opened 2019-07-10 08:58 UTC
**Describe the bug**
The alert text saying that you need to connect to the internet to use chat is misaligned to the alert box; the text exceeds to the dimensions of the alert box.

**To Reproduce**
1. Run Quaver in offline mode
2. Press Chat on Main Menu or Song Select

**Expected behavior**
If the text exceeds to the alert box, start a new line instead.

**Screenshot**
![chat](https://user-images.githubusercontent.com/39328974/60955613-c8db8500-a333-11e9-9969-ddc1b47e3358.PNG)

Desktop
Version:  Canary (as of 7/6)
OS: Win8
-----------
Edit: Screen Resolution: 1366x768
GPU: GeForce 210

**Comment by Swan** [comment] 2019-07-10 13:35
Duplicate of #832

**Closed by Swan** 2019-07-10 13:35 UTC
