### ISSUE TITLE
Drag & Drop doesn't working

### ISSUE THREAD

**Issue by KeepSOBP** [Quaver/Quaver#2413] opened 2020-07-17 06:55 UTC
**Describe the bug**
Title

**To Reproduce**
1. open Quaver
2. drag any files(.mp3, gp) into the game

**Expected behavior**
detect files

**Screenshots**

![image](https://bread.shx.gg/NR1h3p.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC
 - Browser Chrome
 - Version ??

**Additional context**
idk

**Comment by lilxleb** [comment] 2020-07-17 12:58
Press cancel and go out of the editor, and then drag it in.

**Comment by KeepSOBP** [comment] 2020-07-18 01:32
@lilxleb nothing works
![bug](https://bread.shx.gg/y74iby.gif)

**Comment by Swan** [comment] 2020-07-18 14:16
Duplicate of #384. Not sure what's causing this for some users but we're tracking it.

**Closed by Swan** 2020-07-18 14:16 UTC
