### ISSUE TITLE
Audio stopping

### ISSUE THREAD

**Issue by Este2013** [Quaver/Quaver#3232] opened 2021-09-08 14:20 UTC
When I let my pc go in sleep mode, after I make it run again, the game looses all audio. Also, if i plug in headphones or remove them, the audio completely stops too. In either of those cases, nothing i did made the audio run again, apart from closing and relaunching the game completely. 

OS: Windows 10
Steam version 0.29.4

**Comment by Swan** [comment] 2021-11-15 14:54
Duplicate of #569

**Closed by Swan** 2021-11-15 14:54 UTC
