### ISSUE TITLE
Buttons Suddenly Stopped Working

### ISSUE THREAD

**Issue by staravia** [Quaver/Quaver#487] opened 2019-01-08 09:28 UTC
Every button stopped working (but mouse input still registers.)
- Cursor follows mouse and resizes properly when clicked
- Buttons don't react when cursor is hovering over them
- Don't know how to reproduce
- Was not logged in runtime

**Comment by Swan** [comment] 2019-01-23 14:05
Duplicate of #232

**Closed by Swan** 2019-01-23 14:05 UTC
Labels: Input, bug
