### ISSUE TITLE
Skins wont show after subscribed 

### ISSUE THREAD

**Issue by EmilisyayeALT** [Quaver/Quaver#3878] opened 2023-08-24 22:01 UTC
### Skins not appearing even resubbed

I am having this issue over 4 - 5 hours and i do not know what is the matter, i reinstalled to fix installing maps though in game (which didnt work) but when after reinstall all of the skins were gone. I went to the workshop to subscribe my skins again that i use but when installed and restarted quaver, nothing. I redo everything but still nothing shows up, just the default skin.  

### To Reproduce

When downloaded any skin and restarted quaver

### Expected behavior

When i resubscribed skins and restart quaver, they should appear.

### Log Files

[runtime.log](https://github.com/Quaver/Quaver/files/12433707/runtime.log)
[network.log](https://github.com/Quaver/Quaver/files/12433710/network.log)

### Screenshots

![image](https://github.com/Quaver/Quaver/assets/143137037/c939ef3d-6c75-4cc6-b525-f89368e09ef0)
![image](https://github.com/Quaver/Quaver/assets/143137037/3476160e-fe21-49aa-b1af-35b1185bbccb)

**Comment by AiAe** [comment] 2023-08-24 22:05
Have you checked if Steam has started downloading the workshop skins?
This is not Quaver related issue, since if they are not downloaded we cannot load to show them in the dropdown.

Also according to the logs you also have issues logging in is that true?

**Comment by EmilisyayeALT** [comment] 2023-08-24 22:08
it auto logs me in so not really, just that i cant download maps if in "Download Maps" or on Multiplayer

**Comment by EmilisyayeALT** [comment] 2023-08-24 22:08
also i will have a look if its installing it correctly

**Comment by AiAe** [comment] 2023-08-24 22:10
> it auto logs me in so not really, just that i cant download maps if in "Download Maps" or on Multiplayer

So what do u mean exactly by this, you cannot download maps or go to multiplay even when logged in?
Or you just chose not to play online?

**Comment by EmilisyayeALT** [comment] 2023-08-24 22:12
It shows that im logged on but cannot do a single thing, i am not too sure if i am on offline more because people show up on multiplayer and as i am aware you do need to online to view multiplayer, correct me if im wrong

**Comment by EmilisyayeALT** [comment] 2023-08-24 22:48
now i have to get my friends to give me the map files if im gonna play multiplayer with them and it is very annoying (or if single player and i see a map that my friends have, instead of searching it i ask for the file because i know that using "download maps" wont work)

**Comment by AiAe** [comment] 2023-08-25 14:21
@EmilisyayeALT are u familiar with using cmd/powershell, i'd like you to try to run
`ping quavergame.com` and share the results as screenshot here.

If the ping results in "The waiting interval for the request has been exceeded" that means the case is the same. 
In which u can try to run `ping quavergame.com -4` and it will probably ping the site correctly. 

Few days ago another person had not quite the same but similar issues which were caused by his ISP/PC that it uses IPv6 instead IPv4 which was leading to really slow connection and also failing at times.

**Comment by EmilisyayeALT** [comment] 2023-08-25 14:33
![image](https://github.com/Quaver/Quaver/assets/143137037/7c5efd03-117f-41f9-be08-d75f0b3f6107)
this is what it showed up

**Comment by AiAe** [comment] 2023-08-25 14:35
This does look fine, then really i'm unsure whats going on with your connection issues. Even more when it also effects Steam to download the skins your subscribed to.

**Comment by EmilisyayeALT** [comment] 2023-08-25 14:36
Skins showed up also but im not too sure how it happened

**Comment by EmilisyayeALT** [comment] 2023-08-26 10:52
![image](https://github.com/Quaver/Quaver/assets/143137037/1336369c-e653-4db0-a9ed-bfe04c2fccb7)
also when opened its saying that it cannot connect to the server

**Comment by Swan** [comment] 2023-08-30 14:09
> Skins showed up also but im not too sure how it happened 

Is your issue fixed now or do you still need help?

**Comment by EmilisyayeALT** [comment] 2023-08-30 14:24
Skins is fixed just that there is a another issue

**Comment by EmilisyayeALT** [comment] 2023-08-30 14:26
(about connection issues)

**Comment by Swan** [comment] 2023-08-30 14:44
I'm not entirely sure why that's happening, but it's not on our end. Whenever this happens with other users, it's usually an issue with their own setup.

The best advice I can give you is the following:

1. Restart your computer
2. Update your computer
3. Double check any network settings such as vpn, proxy, firewall, wifi, any software that might be interfering, etc

**Comment by Swan** [comment] 2023-09-05 20:00
Closing since this is unactionable on our end. If you need further support, you could try asking in the #help channel of our [Discord](https://discord.gg/quaver).

**Closed by Swan** 2023-09-05 20:00 UTC
Labels: Needs OP Response
