### ISSUE TITLE
"Perfectionist" achievement only unlocked when obtaining "Starvelous" achievement.

### ISSUE THREAD

**Issue by c272** [Quaver/Quaver#3417] opened 2022-03-11 17:25 UTC
**Describe the bug**
The "Perfectionist" achievement does not seem to properly unlock after playing a song with all perfects or above.
In addition, the achievement only unlocked for me when I attained the "Starvelous" achievement on another map.
Maybe a regression of #2965 et al?

**To Reproduce**
1. Play a map with no hits below perfect.
2. Receive no achievement.
3. Play a map with the "Starvelous" criteria (no marvelous hits).
4. Receive both achievements at once.

**Expected behavior**
The "perfectionist" achievement should unlock when all marvelous/perfect hits are played.
The "starvelous" achievement should not unlock the "perfectionist" achievement.

**Desktop:**
 - OS: Windows 10
 - Browser: N/A
 - Version: Quaver latest.

**Comment by Swan** [comment] 2022-03-13 18:49
Duplicate of https://github.com/Quaver/Nameless/issues/8

**Closed by Swan** 2022-03-13 18:49 UTC
