### ISSUE TITLE
Lookup osu! songs folder location from osu! config when reading from osu!.db

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#2372] opened 2020-07-14 12:45 UTC
Related to #2371 

Database read breaks if the songs folder isn't the default osu!/Songs.

osu! config filename is `osu!.USER.cfg` with the USER being replaced by the current user. Should probably choose the last modified config in this case. The config setting is called `BeatmapDirectory`.

[Relevant code](https://github.com/Quaver/Quaver/blob/ui-redesign/Quaver.Shared/Database/Maps/OtherGameMapDatabaseCache.cs#L273)

**Comment by Swan** [comment] 2020-07-14 15:00
Duplicate of #258

**Closed by Swan** 2020-07-14 15:00 UTC
