### ISSUE TITLE
Re-entering a multiplayer lobby after crashing

### ISSUE THREAD

**Issue by Lelloq** [Quaver/Quaver#2293] opened 2020-07-11 17:25 UTC
**Describe the bug**
Game drops to 2-3fps then crashes shortly after re-entering the multiplayer lobby

[6:17:08] - RUNTIME - DEBUG: OS: Microsoft Windows 10.0.18362
[6:17:08] - RUNTIME - IMPORTANT: Started IPC server on port: 43596
[6:17:08] - RUNTIME - IMPORTANT: Config file has been successfully read.
[6:17:08] - RUNTIME - IMPORTANT: Successfully initialized and logged into Steam as : Señor Ching Wong <76561198128366449>
[6:17:08] - RUNTIME - IMPORTANT: Found 0 subscribed workshop items | # of subscribed: 1 | Entries: 1
[6:17:09] - RUNTIME - IMPORTANT: Config file has been successfully read.
[6:17:09] - RUNTIME - DEBUG: BASS options: DevicePeriod = -1, DeviceBufferLength = 10
[6:17:09] - RUNTIME - DEBUG: BASS version: 2.4.13.8
[6:17:10] - RUNTIME - IMPORTANT: Config file has been successfully read.
[6:17:10] - RUNTIME - IMPORTANT: Scores table has been created
[6:17:10] - RUNTIME - IMPORTANT: Map Database has been created
[6:17:10] - RUNTIME - IMPORTANT: Found 144 .qua files inside the song directory
[6:17:10] - RUNTIME - IMPORTANT: OtherGameMaps table has been created.
[6:17:10] - RUNTIME - IMPORTANT: Starting sync of other game maps...
[6:17:11] - RUNTIME - IMPORTANT: Playlist Table has been created
[6:17:11] - RUNTIME - IMPORTANT: PlaylistMap table has been created
[6:17:11] - RUNTIME - IMPORTANT: Loaded osu! playlist: bridge w/ 21 maps!
[6:17:11] - RUNTIME - IMPORTANT: Loaded osu! playlist: Chordjacc w/ 251 maps!
[6:17:11] - RUNTIME - IMPORTANT: Loaded osu! playlist: dav fc w/ 5 maps!
[6:17:11] - RUNTIME - IMPORTANT: Loaded osu! playlist: Group Stage 7k 2019 w/ 9 maps!
[6:17:11] - RUNTIME - IMPORTANT: Loaded osu! playlist: Hard Guage Journal w/ 2 maps!
[6:17:11] - RUNTIME - IMPORTANT: Loaded osu! playlist: Speedy Boi w/ 66 maps!
[6:17:11] - RUNTIME - IMPORTANT: Loaded osu! playlist: virbo w/ 133 maps!
[6:17:11] - RUNTIME - IMPORTANT: QuaverSettings table has been created
[6:17:11] - RUNTIME - IMPORTANT: Found 0 maps that have outdated difficulty ratings. Scheduling recalculation upon enteringselect.
[6:17:11] - RUNTIME - IMPORTANT: JudgementWindows table has been created
[6:17:11] - RUNTIME - IMPORTANT: Created preset judgement windows `Standard*` - Marv: 18 | Perf: 43 | Great: 76 | Good: 106 | Okay: 127 | Miss: 164
[6:17:11] - RUNTIME - IMPORTANT: Created preset judgement windows `Peaceful` - Marv: 23 | Perf: 57 | Great: 101 | Good: 141 | Okay: 169 | Miss: 218
[6:17:11] - RUNTIME - IMPORTANT: Created preset judgement windows `Lenient` - Marv: 21 | Perf: 52 | Great: 91 | Good: 128 | Okay: 153 | Miss: 198
[6:17:11] - RUNTIME - IMPORTANT: Created preset judgement windows `Chill` - Marv: 19 | Perf: 47 | Great: 83 | Good: 116 | Okay: 139 | Miss: 180
[6:17:11] - RUNTIME - IMPORTANT: Created preset judgement windows `Strict` - Marv: 16 | Perf: 39 | Great: 69 | Good: 96 | Okay: 115 | Miss: 149
[6:17:11] - RUNTIME - IMPORTANT: Created preset judgement windows `Tough` - Marv: 14 | Perf: 35 | Great: 62 | Good: 87 | Okay: 104 | Miss: 135
[6:17:11] - RUNTIME - IMPORTANT: Created preset judgement windows `Extreme` - Marv: 13 | Perf: 32 | Great: 57 | Good: 79 | Okay: 95 | Miss: 123
[6:17:11] - RUNTIME - IMPORTANT: Created preset judgement windows `Impossible` - Marv: 8 | Perf: 20 | Great: 35 | Good: 49 | Okay: 59 | Miss: 76
[6:17:11] - RUNTIME - IMPORTANT: UserProfile table has been created
[6:17:11] - RUNTIME - DEBUG: Loaded font: Lato-Regular
[6:17:11] - RUNTIME - DEBUG: Loaded font: Lato-Semibold
[6:17:11] - RUNTIME - DEBUG: Loaded font: Lato-Bold
[6:17:11] - RUNTIME - DEBUG: Loaded font: Lato-Light
[6:17:11] - RUNTIME - DEBUG: Loaded font: Lato-Heavy
[6:17:11] - RUNTIME - DEBUG: Loaded font: Lato-Black
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/HitObjects/note-hitobject-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/HitObjects/note-holdhitobject-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/HitObjects/note-holdbody-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/HitObjects/note-holdend-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/Receptors/receptor-up-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/Receptors/receptor-down-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/Editor/note-hitobject-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/Editor/note-holdbody-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys4/Editor/note-holdend-5.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys7/HitObjects/note-hitobject-8.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys7/HitObjects/note-holdhitobject-8.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys7/HitObjects/note-holdbody-8.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys7/HitObjects/note-holdend-8.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys7/Editor/note-hitobject-8.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys7/Editor/note-holdbody-8.png. Using default!
[6:17:11] - RUNTIME - ERROR: Failed to load: Quaver.Resources/Textures/Skins/Bar/Keys7/Editor/note-holdend-8.png. Using default!
[6:17:12] - RUNTIME - DEBUG: Currently running Quaver version: `0.19.2`
[6:17:12] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Alpha'. w/ 0 ms delay
[6:17:14] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Menu'. w/ 200 ms delay
[6:17:14] - RUNTIME - IMPORTANT: Changed to Screen 'Menu'
[6:17:14] - RUNTIME - IMPORTANT: Starting other game sync thread.
[6:17:15] - RUNTIME - DEBUG: Selected new jukebox track (0): 辑规眠惑苛(ZUN) - The Witch's Dance Party - Original [7k - hard lvl 64] 
[6:17:16] - RUNTIME - IMPORTANT: Cleared previously available chat channels
[6:17:16] - RUNTIME - IMPORTANT: Received friends list containing 0 users.
[6:17:16] - RUNTIME - IMPORTANT: Received Twitch Connection Status: Connected: False | Username: 
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #announcements
[6:17:16] - RUNTIME - IMPORTANT: Joined chat channel: #announcements | Get the latest on what happens!
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #quaver
[6:17:16] - RUNTIME - IMPORTANT: Joined chat channel: #quaver | General discussion about Quaver. Type /help for more information!
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #offtopic
[6:17:16] - RUNTIME - IMPORTANT: Joined chat channel: #offtopic | Talk about anything you'd like! Keep it safe for work, however!
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_6bd07b4e834ed22430afa84d5d395b46
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_6bd07b4e834ed22430afa84d5d395b46
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_4ba9d8eca0f7ffc4fa9d626254d9ebda
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_92fc34f7a152b16c667e1524850455f5
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_92fc34f7a152b16c667e1524850455f5
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_654c8d46e79db62dcbbe4e2389ccb342
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_654c8d46e79db62dcbbe4e2389ccb342
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_c7ddd00c43eeb003a5d83f0f73ff8d7c
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_c7ddd00c43eeb003a5d83f0f73ff8d7c
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_43b5d7a9192cedeedbcf135e53c216a2
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_43b5d7a9192cedeedbcf135e53c216a2
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_90d747f906d08a25151cf692ca54d8b5
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_90d747f906d08a25151cf692ca54d8b5
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_d8129a24c5bb16719ecd6130aaac2479
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_d8129a24c5bb16719ecd6130aaac2479
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_4b7d40b76629204e68236f4d3709dfd7
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_4b7d40b76629204e68236f4d3709dfd7
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_ad0de92779e99392985e12cf52ae4ccf
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_ad0de92779e99392985e12cf52ae4ccf
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_fef901f5cab4e5b0f0f368fd190e45ba
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_fef901f5cab4e5b0f0f368fd190e45ba
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_21d7a049b80c2c733ac6c7832f5e5648
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_21d7a049b80c2c733ac6c7832f5e5648
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_65009a7fc8a9b5db1dbfcf0f8d65d4c2
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_65009a7fc8a9b5db1dbfcf0f8d65d4c2
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_11823cd1132322450fbbc9bb0eb0729d
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_11823cd1132322450fbbc9bb0eb0729d
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_645ca999ba1e7c473a1fde5c48dad54d
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_645ca999ba1e7c473a1fde5c48dad54d
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_e70e80419099b1866ed6f76960dda3ee
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_e70e80419099b1866ed6f76960dda3ee
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_2b3e70dd6545dc7f76ddfa59393c5c5b
[6:17:16] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_2b3e70dd6545dc7f76ddfa59393c5c5b
[6:17:17] - RUNTIME - IMPORTANT: Received available chat channel: #multiplayer_e9758dde71ca3bf59bd932c339bb0859
[6:17:17] - RUNTIME - IMPORTANT: Received available chat channel: #multi_team_e9758dde71ca3bf59bd932c339bb0859
[6:17:17] - RUNTIME - IMPORTANT: Scheduled screen change to: 'Lobby'. w/ 0 ms delay
[6:17:17] - RUNTIME - IMPORTANT: Changed to Screen 'Lobby'
[6:17:21] - RUNTIME - IMPORTANT: Joined chat channel: #multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda | Multiplayer Game Chat Discussion
[6:17:22] - RUNTIME - IMPORTANT: Changed to Screen 'Multiplayer'
[6:17:22] - RUNTIME - IMPORTANT: Fetched 0 Global scores for map:  | Has PB: False
[6:17:22] - RUNTIME - IMPORTANT: Fetching message history for channel: #multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda
[6:17:22] - RUNTIME - ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quaver.Shared.Screens.Selection.UI.Preview.SelectMapPreviewContainer.HandleLoadGameplayScreen(Map map, CancellationToken token)
[6:17:22] - RUNTIME - IMPORTANT: Finished Fetching message history for channel: #multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda w/ 20 messages!
[6:17:22] - RUNTIME - IMPORTANT: Flushed 20 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message history queue.
[6:17:33] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:17:33] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:17:36] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:17:38] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:17:43] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:17:55] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:17:56] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:17:56] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:17:59] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:18:05] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:18:11] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:18:12] - RUNTIME - IMPORTANT: Flushed 2 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:18:13] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.
[6:18:14] - RUNTIME - IMPORTANT: Flushed 1 messages from the `#multiplayer_4ba9d8eca0f7ffc4fa9d626254d9ebda` message queue.

**Comment by Swan** [comment] 2020-07-11 18:56
Duplicate of https://github.com/Quaver/Quaver/issues/2258

**Closed by Swan** 2020-07-11 18:56 UTC
