### ISSUE TITLE
Audio disappearing when removing output device

### ISSUE THREAD

**Issue by ElectroYan** [Quaver/Quaver#1430] opened 2020-01-09 19:42 UTC
**Describe the bug**
When removing/disabling the current audio device streaming Quaver and plugging it back in/enabling there's no audio from Quaver anymore, neither effects nor music unless the game restarts.

**To Reproduce**
1. Physically remove your used audio device
OR
1. Disable the device in the sound manager
2. Plug it back in / enable it again
3. No audio

**Expected behavior**
Audio?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Quaver Version: newest - rebuild

**Comment by Swan** [comment] 2020-01-17 16:52
Duplicate of #569

**Closed by Swan** 2020-01-17 16:52 UTC
Labels: Audio, Requires Wobble
