### ISSUE TITLE
Headphone Removal Causing Songs To Not Play Sound

### ISSUE THREAD

**Issue by BreadddSticksss** [Quaver/Quaver#3347] opened 2021-12-31 00:12 UTC
Quaver will go through a whole list of songs when I unplug my headphones, I can play the maps though, just with no music nor hit-sounds.
**To Reproduce**

1. Open Quaver
2. Play 1 or 2 songs
3. Unplug headphones
4. The bug appears

**Expected behavior**
Songs should start seeking and would not have any music.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Swan** [comment] 2022-01-03 01:49
Duplicate of #569

**Closed by Swan** 2022-01-03 01:49 UTC
