### ISSUE TITLE
"Shortcut-safe mode" option while in gameplay

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#2439] opened 2020-07-20 16:20 UTC
**Is your feature request related to a problem? Please describe.**
A common issue in vsrgs is getting your play ruined by a misclick on a windows shortcut like the windows key, alt-tab and such. Having just a setting to turn on and not having to fear anything bad happening would be very nice to bring in the game.

**Describe the solution you'd like**
Since it would be counter intuitive to disable these by default, and some people might even keep these shortcuts even in game, it should be an opt-in feature. Either in misc or gameplay settings.

**Describe alternatives you've considered**
To avoid settings clutter, and if this feature is considered too advanced, it could only remain in the configs (or as advanced setting if #2443 is implemented)

**Additional context**
Third party software can also do the job but require sketchy programs to run, advanced configuratiin and it's currently not possible only during gameplay anyway.

**Comment by Adrriii** [comment] 2020-07-22 12:05
Example of issue that would be solved by this feature #2068

**Comment by Swan** [comment] 2020-11-25 21:01
Duplicate of #935

**Closed by Swan** 2020-11-25 21:01 UTC
Labels: Gameplay, Input
