### ISSUE TITLE
0.1 and lower SV value automatically turns into 0.1 when importing map from other games

### ISSUE THREAD

**Issue by AHx14** [Quaver/Quaver#3274] opened 2021-10-10 09:48 UTC
As mentioned in the title, it has been consistent for me that all of the maps with SV that I import from osu! has SV value ranging from 0.01-0.09 be automatically updated to 0.1

**Comment by Illuminati-CRAZ** [comment] 2021-10-10 09:58
duplicate of #2220

**Closed by Illuminati-CRAZ** 2021-10-10 09:58 UTC
