### ISSUE TITLE
hit animation also rated with notes

### ISSUE THREAD

**Issue by apple1367** [Quaver/Quaver#2469] opened 2020-07-24 15:37 UTC
**Describe the bug**
when i rate the map and plays it, hit effect is also rated.

**To Reproduce**
1. apply any skin that has hit effect (longer hit effect makes it easier to find)
2. rate any map.
3. play it.

**Expected behavior**
hit effect has to come out normaly

**Screenshots**
i dont know how to make gif

**Desktop (please complete the following information):**
windows 10 64bit 2004
newest version at 2020 07 25

**Additional context**

**Comment by Swan** [comment] 2020-07-25 14:23
Duplicate of #2227

**Closed by Swan** 2020-07-25 14:23 UTC
