### ISSUE TITLE
[redesign] Ubuntu 19.10 Cursor stuck when out of fullscreen Quaver

### ISSUE THREAD

**Issue by Adrriii** [Quaver/Quaver#1195] opened 2019-10-29 15:03 UTC
**Description**
Game is fullscreen, mouse at a certain position. When alt-tabbing out of Quaver, the cursor is stuck to its quaver position (when moving, it goes back to where it was). Closing Quaver fixes it.

**Reproduce**
1. Open Quaver
2. Set cursor somewhere
3. Alt-tab to any other app
4. Try to move cursor

OS: Ubuntu 19.10
Quaver Build: latest redesign branch

**Comment by YaLTeR** [comment] 2020-04-15 18:22
#1661 seems like a duplicate of this (and it has more discussion).

**Closed by YaLTeR** 2020-04-15 18:22 UTC
Labels: Bug, Linux, Requires Wobble
