### ISSUE TITLE
Replay saving bugged with mirror mod

### ISSUE THREAD

**Issue by Skibble1** [Quaver/Quaver#1091] opened 2019-09-28 21:35 UTC
When a replay is saved from a play using mirror,
the replay will use the mirrored inputs on the non mirrored map.
This causes the plays judgements to become inverted and completely off.

1. Play any map with mirror
2. (Important) Exit to song selection from results screen
3. Open the result screen again and play the replay
4. Mirror will no longer apply in replay

 - OS: Windows 10 Enterprise
 - Browser: Firefox
 - Version: Canary v0.17.0

If the replay is played before exiting results, it will work correctly. However, even after it's played correctly if will still become bugged after exiting to the song select screen.

**Comment by YaLTeR** [comment] 2019-11-07 19:35
Duplicate of #911

**Closed by YaLTeR** 2019-11-07 19:35 UTC
Labels: Bug, Replays
