### ISSUE TITLE
Retry or quit during fail animation

### ISSUE THREAD

**Issue by loafusofbread** [Quaver/Quaver#2395] opened 2020-07-15 22:55 UTC
This one is pretty straightforward. Having to wait for an animation telling you that you've failed when you already know and want to hurry up and retry/exit is pretty frustrating because it removes control from the player for no reason, impeding their flow and making them wait when they already know what they're going to do next. Additionally, taking control away from the player negatively contributes to how the game feels by making it clunky and hard to work with (player has to adjust to the game, not what you want). Allowing the player to retry or exit during the fail animation would eliminate this frustration.

**Comment by Swan** [comment] 2020-07-16 12:55
Duplicate of #2349

**Closed by Swan** 2020-07-16 12:55 UTC
