### ISSUE TITLE
Difficulty bar does not have transparent background on the last difficulty of a mapset

### ISSUE THREAD

**Issue by QiuFeng54321** [Quaver/Quaver#3583] opened 2022-08-03 03:35 UTC
**Describe the bug**
From what I saw it seems like the last difficulty of the map is not showing transparent difficulty bars and it has a black background.

**To Reproduce**
1. Click on a mapset
2. See this bug on the last diff of the map

**Expected behavior**
A transparent background of difficulty bar of the last difficulty of the mapset.

**Screenshots**
![Screen Shot 2022-08-03 at 11 26 31 AM](https://user-images.githubusercontent.com/32996262/182518025-0ff6869d-d590-4dea-a6a7-6e165f0347fc.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15
 - Version canary 07.19.2022

**Comment by Kizuna-dev** [comment] 2022-08-03 03:51
Can reproduce, seems to be a side effect of https://github.com/Quaver/Wobble/pull/125

**Comment by Swan** [comment] 2022-08-20 12:58
Fixed in the latest build

**Closed by Swan** 2022-08-20 12:58 UTC
Labels: Bug, Song Select
