### ISSUE TITLE
Display resolution with Windows' Scaling becomes unusable

### ISSUE THREAD

**Issue by semmick** [Quaver/Quaver#2420] opened 2020-07-18 00:53 UTC
Quaver will use the resolution given in-game, but then scale it alongside Windows' Scaling feature available in the Display settings. What this means is that viewing the game in a resolution that matches my screen (3000x2000) will still be scaled up so that only a quarter of the screen is visible. Remedying this by lowering the in-game resolution and keeping a consistent scaling results in the Quaver window looking "low-res."

To reproduce, set resolution to monitor's max resolution. Then, go to _Display Settings_ (by right-clicking the desktop background). Under _Scale and Layout_, set it to any scaling greater than 100% (I personally use 200%). Go back into Quaver and see how the game scales alongside Windows but maintains the previous resolution to make the window large. 

**Expected behavior**
I would expect Quaver to ignore the scaling from Windows. Other games don't seem to have the issue of scaling with the Windows _Scale and Layout_. And if I'm the only one who is experiencing this, then that's alright as well. 

**Screenshots**

![image](https://user-images.githubusercontent.com/68450649/87840582-45614780-c855-11ea-9397-daa599b12c01.png) This is what the screen looks like immediately after setting the in-game resolution to match my monitor.

![image](https://user-images.githubusercontent.com/68450649/87840627-8bb6a680-c855-11ea-8352-969beafffff6.png)
This is what happens after turning off the Windows' scaling effect. 

![image](https://user-images.githubusercontent.com/68450649/87840663-b30d7380-c855-11ea-8e53-8e05f526b80f.png)
This is what happens when I lower the resolution, turn on the Windows' scaling effect to 200%, and then full-screen the Quaver window (so it decides the resolution to fit the screen, which is a cool feature btw).

**Desktop (please complete the following information):**
Device: Surface Book 2
 OS: Windows 10 Version	10.0.18363 Build 18363
Quaver build 0.20.0

**Additional context**
Again, I'm happy if this is a problem that only affects me. I doubt many others use the Scaling feature. I figured I should pass it along anyway

**Comment by Swan** [comment] 2020-07-18 14:17
Duplicate of #362

**Closed by Swan** 2020-07-18 14:17 UTC
