### ISSUE TITLE
Difficulty names in maps browser do not match actual difficulties

### ISSUE THREAD

**Issue by kyle-huo** [Quaver/Quaver#2976] opened 2021-05-06 00:54 UTC
In the maps browser, there is the option to preview the difficulties by mousing over the difficulty listed on the mapset. However, the names of the difficulties do not properly correspond to the right difficulty level.
Here is an example of the issue. As shown, the preview difficulties are "Poke's Hard - 02.30; Put it on a necklace - 07.51, Sya's Normal - 13.46", while the actual difficulties are "Sya's Normal - 02.30, Poke's Hard - 07.51, Put it on a necklace - 13.46". 

![1](https://user-images.githubusercontent.com/77560348/117226753-3048ab80-adca-11eb-9d21-e0f7de84ed79.png)
![2](https://user-images.githubusercontent.com/77560348/117226760-33dc3280-adca-11eb-9985-73cedae3fce3.png)

I couldn't figure out the exact pattern in which these were getting mismatched, but it appears to affect all maps. I am not sure if this affects all users, but I don't believe I have any settings or special circumstances that would cause this.

**Comment by Illuminati-CRAZ** [comment] 2021-05-09 00:33
duplicate of #2539

**Closed by Illuminati-CRAZ** 2021-05-09 00:33 UTC
