### ISSUE TITLE
Weird nsv turn off when it's active

### ISSUE THREAD

**Issue by RiderZaCoder** [Quaver/Quaver#4173] opened 2024-06-09 10:20 UTC
### Describe the bug

I was trying to learn sv maps via preview with nsv on so I can look at the raw charting. When I use tab to try to play the raw chart sv's turn back on. I have no idea if this was meant to happen

### To Reproduce

I don't know-

### Expected behavior

For sv's not to turn on when I want to try the raw charting

### Log Files

None

### Screenshots

https://github.com/Quaver/Quaver/assets/105953005/9c16b5b8-8097-4320-a59c-17f0c64295e4

**Comment by Warp9000** [comment] 2024-06-11 22:07
https://github.com/Quaver/Quaver/issues/3785

**Comment by Warp9000** [comment] 2024-06-27 21:43
duplicate of above

**Closed by Warp9000** 2024-06-27 21:43 UTC
Labels: Bug
