### ISSUE TITLE
No sound effect after launch.

### ISSUE THREAD

**Issue by su226** [Quaver/Quaver#4241] opened 2024-08-01 16:10 UTC
### Describe the bug

No sound effect after launch, including button sound, hitsound etc. Switch to another audio output device (and optionally switch back) will resolve this.

OS: Arch Linux
Sound system: pipewire & pipewire-jack

### To Reproduce

1. Start Quaver.
2. You'll get no sound effect, only music.
3. Switch to another audio output device and switch back.
4. Effects become normal.

### Expected behavior

Both music and effect played.

### Log Files

[network.log](https://github.com/user-attachments/files/16459168/network.log)
[runtime.log](https://github.com/user-attachments/files/16459170/runtime.log)

### Screenshots

https://github.com/user-attachments/assets/cdd7453c-8b36-446d-94bd-12ea78e630aa

**Comment by Warp9000** [comment] 2024-08-01 16:18
duplicate of https://github.com/Quaver/Quaver/issues/4193

**Closed by Warp9000** 2024-08-01 16:18 UTC
Labels: Bug
