### ISSUE TITLE
Visual offset adjustment like bms clients

### ISSUE THREAD

**Issue by Connormgs** [Quaver/Quaver#1636] opened 2020-03-01 19:20 UTC
**Is your feature request related to a problem? Please describe.**
I want my hit position slightly above the judge line but can't set the visual offset like that. 

**Describe the solution you'd like**
The ability to adjust visual offset like a BMS client so you can set your hit position above or below the judge line without the judge line moving. 

**Describe alternatives you've considered**
Editing the skin receptor images is a pain. 

**Additional context**
Greater flexibility of tweaking your playfield.

**Comment by YaLTeR** [comment] 2020-03-02 04:38
Duplicate of https://github.com/Quaver/Quaver/issues/855?

**Comment by staravia** [comment] 2020-03-02 07:55
I proposed something like this ages ago

https://github.com/Quaver/Quaver/issues/175

**Closed** 2020-03-02 14:58 UTC
Labels: Gameplay, Settings
