### ISSUE TITLE
CH Keyboard Keys "öäü" dont work as keybinds

### ISSUE THREAD

**Issue by DrLou04** [Quaver/Quaver#2300] opened 2020-07-11 20:28 UTC
**Describe the bug**
The Bug is that the game doesnt detect "öäü" as a keybind on CH keyboards (swiss), instead of the key, it writes None. I asked another player who has a DE (german) Keyboard and he said he could use "öäü" as keybinds, so i think it only affects CH Keyboards

**To Reproduce**
1. Go to 'OPTIONS'
2. Click on 'Input'
3. Scroll to 'gameplay'
4. Click  "öäü" as a keybind on a CH keyboard.
5. Then it will show as None

**Expected behavior**
I expected that "öäü" apear on the keybinds section, and being able to use these buttons

**Screenshots**
https://imgur.com/DQazBdK In this Photo i wanted to use ASD SPACE ÖÄ$, but it only shows ASD SPACE None $

**Desktop (please complete the following information):**
 - Version Quaver on the 11.07.2020 Downloaded it today

**Additional context**
I think the problem is pretty easy to understand.

**Comment by llAnasll** [comment] 2020-07-11 20:32
Duplicate of #886

**Closed** 2020-11-25 20:53 UTC
Labels: Bug, Configuration
